# Pandas String Operations

In [44]:
import pandas  as pd
import numpy as np

In [45]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day25_pandas_string_operations.csv")

In [46]:
df.head()

,Order_ID,Customer_Name,City,Product,Email,Order_Status
0,4001,sandeep,hyderabad,Laptop,sandeep@example.com,Delivered
1,4002,RAVI,BENGALURU,mouse,RAVI@EXAMPLE.COM,delivered
2,4003,Priya Sharma,Chennai,MONITOR,priya@example.com,RETURNED
3,4004,anil kumar,PUNE,Keyboard,anil@example.com,Delivered
4,4005,DIVYA,Hyderabad,laptop,divya@example.com,cancelled

In [47]:
df.shape

(30, 6)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       30 non-null     int64
 1   Customer_Name  30 non-null     object
 2   City           30 non-null     object
 3   Product        30 non-null     object
 4   Email          30 non-null     object
 5   Order_Status   30 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.5+ KB

In [49]:
df.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Email',
       'Order_Status'],
      dtype='object')

In [50]:
df.describe()

          Order_ID
count    30.000000
mean   4015.500000
std       8.803408
min    4001.000000
25%    4008.250000
50%    4015.500000
75%    4022.750000
max    4030.000000

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
df.isnull().sum()

Order_ID         0
Customer_Name    0
City             0
Product          0
Email            0
Order_Status     0
dtype: int64

# .str.lower() — Convert to lowercase

In [53]:
df["Customer_Name"]=df["Customer_Name"].str.lower()
print(df["Customer_Name"])

0         sandeep
1             ravi
2     priya sharma
3      anil kumar
4            divya
5            kiran
6           meena
7            arjun
8     lakshmi devi
9            rahul
10     sneha reddy
11          vijay
12           pooja
13           manoj
14          harsha
15        asha rao
16          naveen
17          geetha
18         ramesh
19          swathi
20      ajay kumar
21           kavya
22          chandu
23          deepa
24           rohit
25            teja
26         mounika
27             sai
28          nikhil
29          bhavya
Name: Customer_Name, dtype: object

- Example: "SANDEEP" → "sandeep"

In [56]:
df["Email"]=df["Email"].str.lower()
print(df["Email"])

0     sandeep@example.com
1        ravi@example.com
2       priya@example.com
3       anil@example.com
4       divya@example.com
5       kiran@example.com
6       meena@example.com
7       arjun@example.com
8     lakshmi@example.com
9       rahul@example.com
10      sneha@example.com
11      vijay@example.com
12      pooja@example.com
13      manoj@example.com
14     harsha@example.com
15       asha@example.com
16     naveen@example.com
17     geetha@example.com
18     ramesh@example.com
19     swathi@example.com
20       ajay@example.com
21      kavya@example.com
22     chandu@example.com
23      deepa@example.com
24      rohit@example.com
25       teja@example.com
26    mounika@example.com
27        sai@example.com
28     nikhil@example.com
29     bhavya@example.com
Name: Email, dtype: object

In [58]:
df["City"]=df["City"].str.lower()
print(df["City"])

0       hyderabad
1       bengaluru
2         chennai
3            pune
4       hyderabad
5       bengaluru
6         chennai
7            pune
8      hyderabad
9       bengaluru
10        chennai
11           pune
12      hyderabad
13      bengaluru
14        chennai
15           pune
16      hyderabad
17      bengaluru
18        chennai
19           pune
20      hyderabad
21      bengaluru
22        chennai
23           pune
24      hyderabad
25      bengaluru
26        chennai
27           pune
28      hyderabad
29      bengaluru
Name: City, dtype: object

# .str.upper() — Convert to uppercase

In [60]:
df["City"]=df["City"].str.upper()
print(df["City"])

0       HYDERABAD
1       BENGALURU
2         CHENNAI
3            PUNE
4       HYDERABAD
5       BENGALURU
6         CHENNAI
7            PUNE
8      HYDERABAD
9       BENGALURU
10        CHENNAI
11           PUNE
12      HYDERABAD
13      BENGALURU
14        CHENNAI
15           PUNE
16      HYDERABAD
17      BENGALURU
18        CHENNAI
19           PUNE
20      HYDERABAD
21      BENGALURU
22        CHENNAI
23           PUNE
24      HYDERABAD
25      BENGALURU
26        CHENNAI
27           PUNE
28      HYDERABAD
29      BENGALURU
Name: City, dtype: object

- Example: "Hyderabad" → "HYDERABAD"

In [61]:
df["Customer_Name"]=df["Customer_Name"].str.upper()
print(df["Customer_Name"])

0         SANDEEP
1             RAVI
2     PRIYA SHARMA
3      ANIL KUMAR
4            DIVYA
5            KIRAN
6           MEENA
7            ARJUN
8     LAKSHMI DEVI
9            RAHUL
10     SNEHA REDDY
11          VIJAY
12           POOJA
13           MANOJ
14          HARSHA
15        ASHA RAO
16          NAVEEN
17          GEETHA
18         RAMESH
19          SWATHI
20      AJAY KUMAR
21           KAVYA
22          CHANDU
23          DEEPA
24           ROHIT
25            TEJA
26         MOUNIKA
27             SAI
28          NIKHIL
29          BHAVYA
Name: Customer_Name, dtype: object

In [62]:
df["Product"]=df["Product"].str.upper()
print(df["Product"])

0       LAPTOP
1        MOUSE
2      MONITOR
3     KEYBOARD
4       LAPTOP
5       MOUSE
6      MONITOR
7       LAPTOP
8     KEYBOARD
9       LAPTOP
10     MONITOR
11       MOUSE
12    KEYBOARD
13     LAPTOP
14      LAPTOP
15     MONITOR
16       MOUSE
17      LAPTOP
18    KEYBOARD
19      LAPTOP
20     MONITOR
21       MOUSE
22      LAPTOP
23    KEYBOARD
24      LAPTOP
25     MONITOR
26       MOUSE
27      LAPTOP
28    KEYBOARD
29      LAPTOP
Name: Product, dtype: object

# .str.title() — Capitalize each word
- Example: "sandeep sharma" → "Sandeep Sharma"

- Note: Names with special capitalization, such as McDonald, may need custom handling

In [63]:
df["Customer_Name"]=df["Customer_Name"].str.title()
print(df["Customer_Name"])

0         Sandeep
1             Ravi
2     Priya Sharma
3      Anil Kumar
4            Divya
5            Kiran
6           Meena
7            Arjun
8     Lakshmi Devi
9            Rahul
10     Sneha Reddy
11          Vijay
12           Pooja
13           Manoj
14          Harsha
15        Asha Rao
16          Naveen
17          Geetha
18         Ramesh
19          Swathi
20      Ajay Kumar
21           Kavya
22          Chandu
23          Deepa
24           Rohit
25            Teja
26         Mounika
27             Sai
28          Nikhil
29          Bhavya
Name: Customer_Name, dtype: object

# .str.strip() — Remove extra spaces

- Example:

- "  sandeep " → "sandeep

In [68]:
df["Customer_Name"]=df["Customer_Name"].str.strip()
print(df["Customer_Name"])

0          Sandeep
1             Ravi
2     Priya Sharma
3       Anil Kumar
4            Divya
5            Kiran
6            Meena
7            Arjun
8     Lakshmi Devi
9            Rahul
10     Sneha Reddy
11           Vijay
12           Pooja
13           Manoj
14          Harsha
15        Asha Rao
16          Naveen
17          Geetha
18          Ramesh
19          Swathi
20      Ajay Kumar
21           Kavya
22          Chandu
23           Deepa
24           Rohit
25            Teja
26         Mounika
27             Sai
28          Nikhil
29          Bhavya
Name: Customer_Name, dtype: object

In [69]:
df["City"]=df["City"].str.strip()
print(df["City"])

0     HYDERABAD
1     BENGALURU
2       CHENNAI
3          PUNE
4     HYDERABAD
5     BENGALURU
6       CHENNAI
7          PUNE
8     HYDERABAD
9     BENGALURU
10      CHENNAI
11         PUNE
12    HYDERABAD
13    BENGALURU
14      CHENNAI
15         PUNE
16    HYDERABAD
17    BENGALURU
18      CHENNAI
19         PUNE
20    HYDERABAD
21    BENGALURU
22      CHENNAI
23         PUNE
24    HYDERABAD
25    BENGALURU
26      CHENNAI
27         PUNE
28    HYDERABAD
29    BENGALURU
Name: City, dtype: object

# .str.contains() — Search for text
-  Find customers whose names contain "sha"

In [73]:
result = df[df["Customer_Name"].str.contains("sha", case=False, na=False)]

print(result)

    Order_ID Customer_Name     City  Product               Email Order_Status
2       4003  Priya Sharma  CHENNAI  MONITOR   priya@example.com     RETURNED
14      4015        Harsha  CHENNAI   LAPTOP  harsha@example.com     returned
15      4016      Asha Rao     PUNE  MONITOR    asha@example.com    DELIVERED

# .str.replace() — Replace text

In [74]:
df["Email"] = df["Email"].str.replace("EXAMPLE.COM","example.com",case=False,regex=False)

In [75]:
df.head()

,Order_ID,Customer_Name,City,Product,Email,Order_Status
0,4001,Sandeep,HYDERABAD,LAPTOP,sandeep@example.com,Delivered
1,4002,Ravi,BENGALURU,MOUSE,ravi@example.com,delivered
2,4003,Priya Sharma,CHENNAI,MONITOR,priya@example.com,RETURNED
3,4004,Anil Kumar,PUNE,KEYBOARD,anil@example.com,Delivered
4,4005,Divya,HYDERABAD,LAPTOP,divya@example.com,cancelled

- Example: "RAVI@EXAMPLE.COM" → "RAVI@example.com"

In [77]:
df["Order_Status"] = df["Order_Status"].str.lower()

- This converts "DELIVERED", "Delivered", and "delivered" to the same lowercase format.

# .str.split() — Split text into parts

In [78]:
df["Customer_Name"].str.split()

0           [Sandeep]
1              [Ravi]
2     [Priya, Sharma]
3       [Anil, Kumar]
4             [Divya]
5             [Kiran]
6             [Meena]
7             [Arjun]
8     [Lakshmi, Devi]
9             [Rahul]
10     [Sneha, Reddy]
11            [Vijay]
12            [Pooja]
13            [Manoj]
14           [Harsha]
15        [Asha, Rao]
16           [Naveen]
17           [Geetha]
18           [Ramesh]
19           [Swathi]
20      [Ajay, Kumar]
21            [Kavya]
22           [Chandu]
23            [Deepa]
24            [Rohit]
25             [Teja]
26          [Mounika]
27              [Sai]
28           [Nikhil]
29           [Bhavya]
Name: Customer_Name, dtype: object

- Example: "Priya Sharma" → ["Priya", "Sharma"]

In [79]:
df["First_Name"] = (
    df["Customer_Name"]
    .str.strip()
    .str.split()
    .str[0])
print(df[["Customer_Name", "First_Name"]].head())

  Customer_Name First_Name
0       Sandeep    Sandeep
1          Ravi       Ravi
2  Priya Sharma      Priya
3    Anil Kumar       Anil
4         Divya      Divya

# .str.startswith() and .str.endswith()

In [81]:
# Emails that start with "s"
df[df["Email"].str.startswith("s", na=False)]

,Order_ID,Customer_Name,City,Product,Email,Order_Status,First_Name
0,4001,Sandeep,HYDERABAD,LAPTOP,sandeep@example.com,delivered,Sandeep
10,4011,Sneha Reddy,CHENNAI,MONITOR,sneha@example.com,delivered,Sneha
19,4020,Swathi,PUNE,LAPTOP,swathi@example.com,returned,Swathi
27,4028,Sai,PUNE,LAPTOP,sai@example.com,cancelled,Sai

In [82]:
# Emails that end with ".com"
df[df["Email"].str.endswith(".com", na=False)]

,Order_ID,Customer_Name,City,Product,Email,Order_Status,First_Name
0,4001,Sandeep,HYDERABAD,LAPTOP,sandeep@example.com,delivered,Sandeep
1,4002,Ravi,BENGALURU,MOUSE,ravi@example.com,delivered,Ravi
2,4003,Priya Sharma,CHENNAI,MONITOR,priya@example.com,returned,Priya
4,4005,Divya,HYDERABAD,LAPTOP,divya@example.com,cancelled,Divya
5,4006,Kiran,BENGALURU,MOUSE,kiran@example.com,delivered,Kiran
6,4007,Meena,CHENNAI,MONITOR,meena@example.com,returned,Meena
7,4008,Arjun,PUNE,LAPTOP,arjun@example.com,delivered,Arjun
8,4009,Lakshmi Devi,HYDERABAD,KEYBOARD,lakshmi@example.com,returned,Lakshmi
9,4010,Rahul,BENGALURU,LAPTOP,rahul@example.com,delivered,Rahul
10,4011,Sneha Reddy,CHENNAI,MONITOR,sneha@example.com,delivered,Sneha
11,4012,Vijay,PUNE,MOUSE,vijay@example.com,cancelled,Vijay
12,4013,Pooja,HYDERABAD,KEYBOARD,pooja@example.com,delivered,Pooja
13,4014,Manoj,BENGALURU,LAPTOP,manoj@example.com,delivered,Manoj
14,4015,Harsha,CHENNAI,LAPTOP,harsha@example.com,returned,Harsha
15,4016,Asha Rao,PUNE,MONITOR,asha@example.com,delivered,Asha
16,4017,Naveen,HYDERABAD,MOUSE,naveen@example.com,delivered,Naveen
17,4018,Geetha,BENGALURU,LAPTOP,geetha@example.com,cancelled,Geetha
18,4019,Ramesh,CHENNAI,KEYBOARD,ramesh@example.com,delivered,Ramesh
19,4020,Swathi,PUNE,LAPTOP,swathi@example.com,returned,Swathi
20,4021,Ajay Kumar,HYDERABAD,MONITOR,ajay@example.com,delivered,Ajay
21,4022,Kavya,BENGALURU,MOUSE,kavya@example.com,delivered,Kavya
22,4023,Chandu,CHENNAI,LAPTOP,chandu@example.com,cancelled,Chandu
23,4024,Deepa,PUNE,KEYBOARD,deepa@example.com,delivered,Deepa
24,4025,Rohit,HYDERABAD,LAPTOP,rohit@example.com,delivered,Rohit
25,4026,Teja,BENGALURU,MONITOR,teja@example.com,returned,Teja
26,4027,Mounika,CHENNAI,MOUSE,mounika@example.com,delivered,Mounika
27,4028,Sai,PUNE,LAPTOP,sai@example.com,cancelled,Sai
28,4029,Nikhil,HYDERABAD,KEYBOARD,nikhil@example.com,delivered,Nikhil
29,4030,Bhavya,BENGALURU,LAPTOP,bhavya@example.com,delivered,Bhavya