In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day21_retail_filtering.csv")

In [4]:
df.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
1,5002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-03-02,1400
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-03-03,1200
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,NaN,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000

In [5]:
df.shape

(30, 11)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        30 non-null     int64
 1   Customer_Name   29 non-null     object
 2   City            30 non-null     object
 3   Product         30 non-null     object
 4   Category        30 non-null     object
 5   Quantity        29 non-null     float64
 6   Unit_Price_INR  30 non-null     int64
 7   Payment_Method  29 non-null     object
 8   Order_Status    30 non-null     object
 9   Order_Date      30 non-null     object
 10  Revenue_INR     30 non-null     int64
dtypes: float64(1), int64(3), object(7)
memory usage: 2.7+ KB

In [16]:
df.describe()

          Order_ID   Quantity  Unit_Price_INR   Revenue_INR
count    30.000000  30.000000       30.000000     30.000000
mean   5015.500000   1.586207    22055.333333  23503.000000
std       8.803408   0.670421    24043.803235  23631.583651
min    5001.000000   1.000000      650.000000   1200.000000
25%    5008.250000   1.000000     1112.500000   2225.000000
50%    5015.500000   1.293103    14650.000000  14650.000000
75%    5022.750000   2.000000    52750.000000  52750.000000
max    5030.000000   3.000000    58000.000000  58000.000000

In [17]:
df.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Category', 'Quantity',
       'Unit_Price_INR', 'Payment_Method', 'Order_Status', 'Order_Date',
       'Revenue_INR'],
      dtype='object')

In [18]:
df.size

330

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Order_ID          0
Customer_Name     1
City              0
Product           0
Category          0
Quantity          1
Unit_Price_INR    0
Payment_Method    1
Order_Status      0
Order_Date        0
Revenue_INR       0
dtype: int64

In [15]:
df["Customer_Name"]=df["Customer_Name"].fillna(df["Customer_Name"].mode()[0])
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean())
df["Payment_Method"]=df["Payment_Method"].fillna(df["Payment_Method"].mode()[0])

In [20]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Payment_Method    0
Order_Status      0
Order_Date        0
Revenue_INR       0
dtype: int64

In [23]:
df[df["City"]=="Hyderabad"].head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.000000,55000,UPI,Delivered,2026-03-01,55000
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.000000,1200,UPI,Delivered,2026-03-03,1200
5,5006,Priya,Hyderabad,Mouse,Accessories,3.000000,650,Cash,Delivered,2026-03-06,1950
9,5010,Sneha,Hyderabad,Laptop,Electronics,1.000000,54000,UPI,Delivered,2026-03-10,54000
11,5012,Ananya,Hyderabad,Monitor,Electronics,1.586207,14000,Credit Card,Cancelled,2026-03-12,14000

In [27]:
# Delivered orders
df[df["Order_Status"]=="Delivered"].head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
1,5002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-03-02,1400
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-03-03,1200
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
5,5006,Priya,Hyderabad,Mouse,Accessories,3.0,650,Cash,Delivered,2026-03-06,1950

In [30]:
# Orders paid through UPI
df[df["Payment_Method"]=="UPI"].head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-03-03,1200
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
7,5008,Divya,Chennai,Keyboard,Accessories,2.0,1100,UPI,Delivered,2026-03-08,2200
8,5009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-03-09,14500

In [32]:
# Products costing more than ₹10,000
df[df["Unit_Price_INR"]>10000].head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
6,5007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-03-07,56000
8,5009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-03-09,14500

# Filter using multiple conditions
- Use & for AND and | for OR. Put each condition inside parentheses.

In [40]:
# Hyderabad laptop orders
result=df[(df["City"]=="Hyderabad")&(df["Product"]=="Laptop")]
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
9,5010,Sneha,Hyderabad,Laptop,Electronics,1.0,54000,UPI,Delivered,2026-03-10,54000
20,5021,Rohit,Hyderabad,Laptop,Electronics,1.0,51000,UPI,Delivered,2026-03-21,51000
23,5024,Nandini,Hyderabad,Laptop,Electronics,1.0,53500,UPI,Delivered,2026-03-24,53500
26,5027,Karthik,Hyderabad,Laptop,Electronics,1.0,58000,Credit Card,Delivered,2026-03-27,58000
29,5030,Deepa,Hyderabad,Laptop,Electronics,1.0,56000,UPI,Delivered,2026-03-30,56000

In [44]:
# Laptops or monitors
result=df[(df["Product"]=="Monitor")|(df["Product"]=="Laptop")].head()
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
6,5007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-03-07,56000
8,5009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-03-09,14500

In [46]:
# Delivered orders from Bengaluru
resul=df[(df["City"]=="Bengaluru")&(df["Order_Status"]=="Delivered")]
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
6,5007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-03-07,56000
8,5009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-03-09,14500

In [49]:
# Expensive electronics
result=df[(df["Category"]=="Electronics")&(df["Unit_Price_INR"]>20000)].head()
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
6,5007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-03-07,56000
9,5010,Sneha,Hyderabad,Laptop,Electronics,1.0,54000,UPI,Delivered,2026-03-10,54000
13,5014,Pooja,Bengaluru,Laptop,Electronics,1.0,53000,Debit Card,Delivered,2026-03-14,53000

# Use isin() to match multiple values
- Suppose your manager wants orders from Hyderabad, Bengaluru, and Chennai.

In [54]:
cites=["Hyderabad","Bengalure","Chennai","Pune"]
result=df[df["City"].isin(cites)].head()
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-03-03,1200
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
5,5006,Priya,Hyderabad,Mouse,Accessories,3.0,650,Cash,Delivered,2026-03-06,1950

In [57]:
products = ["Laptop", "Monitor"]
result = df[df["Product"].isin(products)].head()
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
6,5007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-03-07,56000
8,5009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-03-09,14500

In [59]:
result = df[~df["Product"].isin(products)].head()
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
1,5002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-03-02,1400
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-03-03,1200
5,5006,Priya,Hyderabad,Mouse,Accessories,3.0,650,Cash,Delivered,2026-03-06,1950
7,5008,Divya,Chennai,Keyboard,Accessories,2.0,1100,UPI,Delivered,2026-03-08,2200
10,5011,Rahul,Chennai,Mouse,Accessories,2.0,750,Cash,Delivered,2026-03-11,1500

# Use between() for ranges
- Find products priced between ₹1,000 and ₹20,000, including both boundaries.

In [62]:
result=df[df["Unit_Price_INR"].between(1000,20000)].head()
print(result[["Product", "Unit_Price_INR"]])

     Product  Unit_Price_INR
2   Keyboard            1200
4    Monitor           15000
7   Keyboard            1100
8    Monitor           14500
11   Monitor           14000

In [65]:
# Find orders with quantity between 2 and 3:
result=df[df["Quantity"].between(2,3)].head()
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
1,5002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-03-02,1400
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
5,5006,Priya,Hyderabad,Mouse,Accessories,3.0,650,Cash,Delivered,2026-03-06,1950
7,5008,Divya,Chennai,Keyboard,Accessories,2.0,1100,UPI,Delivered,2026-03-08,2200
10,5011,Rahul,Chennai,Mouse,Accessories,2.0,750,Cash,Delivered,2026-03-11,1500

# Use query() for readable filtering
- query() lets you write conditions in a string

In [69]:
df.query("City == 'Hyderabad'").head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.000000,55000,UPI,Delivered,2026-03-01,55000
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.000000,1200,UPI,Delivered,2026-03-03,1200
5,5006,Priya,Hyderabad,Mouse,Accessories,3.000000,650,Cash,Delivered,2026-03-06,1950
9,5010,Sneha,Hyderabad,Laptop,Electronics,1.000000,54000,UPI,Delivered,2026-03-10,54000
11,5012,Ananya,Hyderabad,Monitor,Electronics,1.586207,14000,Credit Card,Cancelled,2026-03-12,14000

In [71]:
df.query("Unit_Price_INR>10000").head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000
6,5007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-03-07,56000
8,5009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-03-09,14500

In [77]:
df.query("City == 'Hyderabad' and Product == 'Laptop'")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
9,5010,Sneha,Hyderabad,Laptop,Electronics,1.0,54000,UPI,Delivered,2026-03-10,54000
20,5021,Rohit,Hyderabad,Laptop,Electronics,1.0,51000,UPI,Delivered,2026-03-21,51000
23,5024,Nandini,Hyderabad,Laptop,Electronics,1.0,53500,UPI,Delivered,2026-03-24,53500
26,5027,Karthik,Hyderabad,Laptop,Electronics,1.0,58000,Credit Card,Delivered,2026-03-27,58000
29,5030,Deepa,Hyderabad,Laptop,Electronics,1.0,56000,UPI,Delivered,2026-03-30,56000

In [79]:
# Find products with prices between ₹1,000 and ₹20,000:
df.query("Unit_Price_INR >= 1000 and Unit_Price_INR <= 20000").head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.000000,1200,UPI,Delivered,2026-03-03,1200
4,5005,Ajay,Pune,Monitor,Electronics,2.000000,15000,UPI,Cancelled,2026-03-05,30000
7,5008,Divya,Chennai,Keyboard,Accessories,2.000000,1100,UPI,Delivered,2026-03-08,2200
8,5009,Manoj,Pune,Monitor,Electronics,1.000000,14500,UPI,Returned,2026-03-09,14500
11,5012,Ananya,Hyderabad,Monitor,Electronics,1.586207,14000,Credit Card,Cancelled,2026-03-12,14000

# Handle missing values during filtering
- Our CSV includes some missing values. For example, a customer name is missing in one order.

In [80]:
# Find rows with missing customer names:
df[df["Customer_Name"].isna()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Unit_Price_INR, Payment_Method, Order_Status, Order_Date, Revenue_INR]
Index: []

In [82]:
# Find rows with available customer names:
df[df["Customer_Name"].notna()].head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,5001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-03-01,55000
1,5002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-03-02,1400
2,5003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-03-03,1200
3,5004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-03-04,52000
4,5005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-03-05,30000

In [83]:
# Find rows with missing quantities:
df[df["Quantity"].isna()]

Empty DataFrame
Columns: [Order_ID, Customer_Name, City, Product, Category, Quantity, Unit_Price_INR, Payment_Method, Order_Status, Order_Date, Revenue_INR]
Index: []

In [85]:
# Find delivered laptop orders from Hyderabad and show only selected columns.
result = df.loc[
    (df["City"] == "Hyderabad") &
    (df["Product"] == "Laptop") &
    (df["Order_Status"] == "Delivered"),
    ["Order_ID", "Customer_Name", "City", "Product", "Order_Status"]]
print(result)

    Order_ID Customer_Name       City Product Order_Status
0       5001          Ravi  Hyderabad  Laptop    Delivered
9       5010         Sneha  Hyderabad  Laptop    Delivered
20      5021         Rohit  Hyderabad  Laptop    Delivered
23      5024       Nandini  Hyderabad  Laptop    Delivered
26      5027       Karthik  Hyderabad  Laptop    Delivered
29      5030         Deepa  Hyderabad  Laptop    Delivered

In [88]:
# Find cancelled orders.
result=df[df["Order_Status"]=="Cancelled"]
result

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
4,5005,Ajay,Pune,Monitor,Electronics,2.000000,15000,UPI,Cancelled,2026-03-05,30000
11,5012,Ananya,Hyderabad,Monitor,Electronics,1.586207,14000,Credit Card,Cancelled,2026-03-12,14000
19,5020,Lakshmi,Chennai,Monitor,Electronics,1.000000,14800,Credit Card,Cancelled,2026-03-20,14800

In [91]:
# Find the number of delivered orders.
df[df["Order_Status"]=="Delivered"].sum().head()

Order_ID                                                    120375
Customer_Name    RaviAshaSandeepNehaPriyaArjunDivyaSnehaRahulVi...
City             HyderabadBengaluruHyderabadChennaiHyderabadBen...
Product          LaptopMouseKeyboardLaptopMouseLaptopKeyboardLa...
Category         ElectronicsAccessoriesAccessoriesElectronicsAc...
dtype: object

In [93]:
# Find the number of orders with unit prices above ₹50,000.
df[df["Unit_Price_INR"]>50000].sum().head()

Order_ID                                                     50156
Customer_Name    RaviNehaArjunSnehaPoojaKavyaRohitNandiniKarthi...
City             HyderabadChennaiBengaluruHyderabadBengaluruPun...
Product          LaptopLaptopLaptopLaptopLaptopLaptopLaptopLapt...
Category         ElectronicsElectronicsElectronicsElectronicsEl...
dtype: object

In [94]:
#Calculate revenue from delivered orders.
delivered = df[df["Order_Status"] == "Delivered"]
total_revenue = delivered["Revenue_INR"].sum()
print("Delivered-order revenue:", total_revenue)

Delivered-order revenue: 613930