In [31]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day18_employee_data.csv")

In [33]:
df.head()

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status
0,2001,Ravi,IT,Data Analyst,Hyderabad,24,1,35000.0,4.2,2024-06-10,Active
1,2002,Asha,HR,HR Executive,Bengaluru,29,5,42000.0,4.0,2021-03-15,Active
2,2003,Sandeep,IT,Python Developer,Hyderabad,23,1,40000.0,4.5,2025-01-20,Active
3,2004,Neha,Sales,Sales Executive,Chennai,31,7,38000.0,3.8,2019-08-12,Active
4,2005,Kiran,Finance,Accountant,Pune,35,10,60000.0,NaN,2016-04-01,Active

In [60]:
df.tail()

,Employee_ID,Employee_Name,Department,Job_Role,City,Age,Experience_Years,Monthly_Salary_INR,Performance_Rating,Joining_Date,Employment_Status,Joining_Year
20,2021,Rohit,IT,BI Analyst,Hyderabad,27,3,50000,4.5,2012-12-11,Active,2012
21,2022,Isha,HR,HR Executive,Bengaluru,30,6,46000,4.1,2020-12-07,On Leave,2020
22,2023,Ajay,Finance,Financial Analyst,Pune,38,13,72000,4.4,2013-07-30,Active,2013
23,2024,Nandini,IT,Data Analyst,Hyderabad,25,2,53000,4.6,2024-09-02,Active,2024
24,2025,Teja,Sales,Sales Executive,Chennai,28,4,39000,3.9,2021-02-11,Active,2021

In [34]:
df.shape

(25, 11)

In [61]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Job_Role', 'City', 'Age',
       'Experience_Years', 'Monthly_Salary_INR', 'Performance_Rating',
       'Joining_Date', 'Employment_Status', 'Joining_Year'],
      dtype='object')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         25 non-null     int64
 1   Employee_Name       25 non-null     object
 2   Department          25 non-null     object
 3   Job_Role            25 non-null     object
 4   City                24 non-null     object
 5   Age                 25 non-null     int64
 6   Experience_Years    25 non-null     int64
 7   Monthly_Salary_INR  24 non-null     float64
 8   Performance_Rating  24 non-null     float64
 9   Joining_Date        24 non-null     object
 10  Employment_Status   25 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 2.3+ KB

In [62]:
df["Department"].value_counts()

Department
IT         9
Sales      6
HR         5
Finance    5
Name: count, dtype: int64

In [36]:
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Department            0
Job_Role              0
City                  1
Age                   0
Experience_Years      0
Monthly_Salary_INR    1
Performance_Rating    1
Joining_Date          1
Employment_Status     0
dtype: int64

In [37]:
df["City"]=df["City"].fillna(df["City"].mode()[0])
df["Monthly_Salary_INR"]=df["Monthly_Salary_INR"].fillna(df["Monthly_Salary_INR"].mean())
df["Performance_Rating"]=df["Performance_Rating"].fillna(df["Performance_Rating"].mean())
df["Joining_Date"]=df["Joining_Date"].fillna(df["Joining_Date"].mode()[0])

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Department            0
Job_Role              0
City                  0
Age                   0
Experience_Years      0
Monthly_Salary_INR    0
Performance_Rating    0
Joining_Date          0
Employment_Status     0
dtype: int64

In [40]:
# Convert a The column Using astype()
df["Age"]=df["Age"].astype("int64")
print(df["Age"].astype)

<bound method NDFrame.astype of 0     24
1     29
2     23
3     31
4     35
5     26
6     28
7     30
8     37
9     25
10    32
11    27
12    39
13    28
14    24
15    33
16    29
17    36
18    26
19    31
20    27
21    30
22    38
23    25
24    28
Name: Age, dtype: int64>

In [41]:
# Convert a text column to to Pandas string type:
df["City"]=df["City"].astype("string")
print(df["City"].astype)

<bound method NDFrame.astype of 0     Hyderabad
1     Bengaluru
2     Hyderabad
3       Chennai
4          Pune
5     Hyderabad
6     Bengaluru
7       Chennai
8     Hyderabad
9     Hyderabad
10      Chennai
11    Hyderabad
12         Pune
13    Bengaluru
14    Hyderabad
15      Chennai
16    Bengaluru
17         Pune
18    Hyderabad
19      Chennai
20    Hyderabad
21    Bengaluru
22         Pune
23    Hyderabad
24      Chennai
Name: City, dtype: string>

In [42]:
# Convert joining Date Using to_datetime()
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"],errors="coerce")
print(df["Joining_Date"].astype)

<bound method NDFrame.astype of 0    2024-06-10
1    2021-03-15
2    2025-01-20
3    2019-08-12
4    2016-04-01
5    2022-07-18
6    2021-11-05
7    2020-02-17
8    2014-09-22
9    2024-01-08
10   2018-05-14
11   2022-10-03
12   2012-12-11
13   2021-06-28
14   2025-02-10
15   2017-03-06
16   2020-08-24
17   2015-11-16
18   2023-09-04
19   2019-01-25
20   2012-12-11
21   2020-12-07
22   2013-07-30
23   2024-09-02
24   2021-02-11
Name: Joining_Date, dtype: datetime64[ns]>

In [43]:
df["Joining_Year"] = df["Joining_Date"].dt.year
print(df[["Employee_Name", "Joining_Date", "Joining_Year"]].head())

  Employee_Name Joining_Date  Joining_Year
0          Ravi   2024-06-10          2024
1          Asha   2021-03-15          2021
2       Sandeep   2025-01-20          2025
3          Neha   2019-08-12          2019
4         Kiran   2016-04-01          2016

In [48]:
# Convert salary to numeric
df["Monthly_Salary_INR"] = pd.to_numeric(df["Monthly_Salary_INR"],errors="coerce")
print(df["Monthly_Salary_INR"].dtype)

int64

In [49]:
print(df["Monthly_Salary_INR"].mean())

49875.0

In [52]:
# Salary analysis by department
avg_salary=df.groupby("Department")["Monthly_Salary_INR"].mean()
avg_salary

Department
Finance    65400.000000
HR         45375.000000
IT         50444.444444
Sales      39833.333333
Name: Monthly_Salary_INR, dtype: float64

In [57]:
# Find employees earning more than ₹40,000:
salary=df[df["Monthly_Salary_INR"]>40000].head()
print(salary[["Employee_Name","Department","Monthly_Salary_INR"]])

  Employee_Name Department  Monthly_Salary_INR
1          Asha         HR               42000
4         Kiran    Finance               60000
5         Priya         IT               65000
7         Divya         HR               45000
8         Manoj    Finance               62000

In [59]:
salary=df[df["Monthly_Salary_INR"]<50000].head()
print(salary[["Employee_Name","Department","Monthly_Salary_INR"]])

  Employee_Name Department  Monthly_Salary_INR
0          Ravi         IT               35000
1          Asha         HR               42000
2       Sandeep         IT               40000
3          Neha      Sales               38000
6         Arjun      Sales               40000

In [64]:
print(df["Monthly_Salary_INR"].sum())

1246875

In [65]:
print(df["Monthly_Salary_INR"].max())

75000