In [3]:
import pandas as pd
import numpy as np

In [4]:
orders = pd.read_csv("/Users/nidagallusandeep/Downloads/day31_orders.csv")
customers = pd.read_csv("/Users/nidagallusandeep/Downloads/day31_customers.csv")
products = pd.read_csv("/Users/nidagallusandeep/Downloads/day31_products.csv")

In [8]:
orders.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3101,101,Laptop,1,55000,Delivered,55000
1,3102,102,Mouse,2,700,Delivered,1400
2,3103,103,Keyboard,3,1200,Cancelled,3600
3,3104,104,Monitor,1,14000,Delivered,14000
4,3105,105,Mouse,4,700,Delivered,2800

In [9]:
customers.head()

   Customer_ID Customer_Name        City  Age Membership
0          101          Anil   Hyderabad   24       Gold
1          102        Bhavya   Bengaluru   27     Silver
2          103        Charan     Chennai   22     Bronze
3          104         Divya   Hyderabad   25       Gold
4          105          Esha  Vijayawada   29     Silver

In [10]:
products.head()

      Product Product_Category   Supplier
0      Laptop      Electronics  TechWorld
1       Mouse      Accessories  GadgetHub
2    Keyboard      Accessories     KeyPro
3     Monitor      Electronics    ViewMax
4  Headphones      Accessories  SoundPlus

# 1. Inner Join

In [12]:
pd.merge(orders, customers, on="Customer_ID", how="inner").head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101,101,Laptop,1,55000,Delivered,55000,Anil,Hyderabad,24,Gold
1,3102,102,Mouse,2,700,Delivered,1400,Bhavya,Bengaluru,27,Silver
2,3103,103,Keyboard,3,1200,Cancelled,3600,Charan,Chennai,22,Bronze
3,3104,104,Monitor,1,14000,Delivered,14000,Divya,Hyderabad,25,Gold
4,3105,105,Mouse,4,700,Delivered,2800,Esha,Vijayawada,29,Silver

# 2. Left Join

In [14]:
pd.merge(orders, customers, on="Customer_ID", how="left").head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101,101,Laptop,1,55000,Delivered,55000,Anil,Hyderabad,24.0,Gold
1,3102,102,Mouse,2,700,Delivered,1400,Bhavya,Bengaluru,27.0,Silver
2,3103,103,Keyboard,3,1200,Cancelled,3600,Charan,Chennai,22.0,Bronze
3,3104,104,Monitor,1,14000,Delivered,14000,Divya,Hyderabad,25.0,Gold
4,3105,105,Mouse,4,700,Delivered,2800,Esha,Vijayawada,29.0,Silver

# 3. Right Join

In [15]:
pd.merge(orders, customers, on="Customer_ID", how="right")

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101.0,101,Laptop,1.0,55000.0,Delivered,55000.0,Anil,Hyderabad,24,Gold
1,3106.0,101,Laptop,1.0,55000.0,Returned,55000.0,Anil,Hyderabad,24,Gold
2,3102.0,102,Mouse,2.0,700.0,Delivered,1400.0,Bhavya,Bengaluru,27,Silver
3,3111.0,102,Keyboard,2.0,1200.0,Delivered,2400.0,Bhavya,Bengaluru,27,Silver
4,3103.0,103,Keyboard,3.0,1200.0,Cancelled,3600.0,Charan,Chennai,22,Bronze
5,3104.0,104,Monitor,1.0,14000.0,Delivered,14000.0,Divya,Hyderabad,25,Gold
6,3116.0,104,Keyboard,4.0,1200.0,Delivered,4800.0,Divya,Hyderabad,25,Gold
7,3105.0,105,Mouse,4.0,700.0,Delivered,2800.0,Esha,Vijayawada,29,Silver
8,3107.0,106,Keyboard,2.0,1200.0,Delivered,2400.0,Farhan,Chennai,26,Bronze
9,3108.0,107,Mouse,5.0,700.0,Delivered,3500.0,Gita,Hyderabad,31,Gold
10,3109.0,108,Monitor,1.0,14000.0,Cancelled,14000.0,Hari,Bengaluru,23,Silver
11,3110.0,109,Laptop,1.0,55000.0,Delivered,55000.0,Indu,Chennai,28,Bronze
12,3112.0,110,Monitor,1.0,14000.0,Delivered,14000.0,Kiran,Hyderabad,24,Gold
13,3113.0,111,Mouse,3.0,700.0,Delivered,2100.0,Lavanya,Vijayawada,30,Silver
14,3114.0,112,Laptop,1.0,55000.0,Cancelled,55000.0,Manoj,Bengaluru,27,Bronze
15,3115.0,113,Mouse,2.0,700.0,Delivered,1400.0,Nisha,Hyderabad,22,Gold
16,3117.0,114,Monitor,1.0,14000.0,Returned,14000.0,Omkar,Chennai,26,Silver
17,3118.0,115,Laptop,1.0,55000.0,Delivered,55000.0,Priya,Bengaluru,25,Gold
18,NaN,118,NaN,NaN,NaN,NaN,NaN,Ravi,Hyderabad,32,Bronze

# 4. Outer Join

In [17]:
pd.merge(orders, customers, on="Customer_ID", how="outer").head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101.0,101,Laptop,1.0,55000.0,Delivered,55000.0,Anil,Hyderabad,24.0,Gold
1,3106.0,101,Laptop,1.0,55000.0,Returned,55000.0,Anil,Hyderabad,24.0,Gold
2,3102.0,102,Mouse,2.0,700.0,Delivered,1400.0,Bhavya,Bengaluru,27.0,Silver
3,3111.0,102,Keyboard,2.0,1200.0,Delivered,2400.0,Bhavya,Bengaluru,27.0,Silver
4,3103.0,103,Keyboard,3.0,1200.0,Cancelled,3600.0,Charan,Chennai,22.0,Bronze

In [18]:
inner_df = pd.merge(
    orders, customers,
    on="Customer_ID",
    how="inner")
inner_df.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101,101,Laptop,1,55000,Delivered,55000,Anil,Hyderabad,24,Gold
1,3102,102,Mouse,2,700,Delivered,1400,Bhavya,Bengaluru,27,Silver
2,3103,103,Keyboard,3,1200,Cancelled,3600,Charan,Chennai,22,Bronze
3,3104,104,Monitor,1,14000,Delivered,14000,Divya,Hyderabad,25,Gold
4,3105,105,Mouse,4,700,Delivered,2800,Esha,Vijayawada,29,Silver

In [19]:
left_df = pd.merge(
    orders, customers,
    on="Customer_ID",
    how="left"
)
left_df.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101,101,Laptop,1,55000,Delivered,55000,Anil,Hyderabad,24.0,Gold
1,3102,102,Mouse,2,700,Delivered,1400,Bhavya,Bengaluru,27.0,Silver
2,3103,103,Keyboard,3,1200,Cancelled,3600,Charan,Chennai,22.0,Bronze
3,3104,104,Monitor,1,14000,Delivered,14000,Divya,Hyderabad,25.0,Gold
4,3105,105,Mouse,4,700,Delivered,2800,Esha,Vijayawada,29.0,Silver

In [20]:
right_df = pd.merge(
    orders, customers,
    on="Customer_ID",
    how="right"
)
right_df.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101.0,101,Laptop,1.0,55000.0,Delivered,55000.0,Anil,Hyderabad,24,Gold
1,3106.0,101,Laptop,1.0,55000.0,Returned,55000.0,Anil,Hyderabad,24,Gold
2,3102.0,102,Mouse,2.0,700.0,Delivered,1400.0,Bhavya,Bengaluru,27,Silver
3,3111.0,102,Keyboard,2.0,1200.0,Delivered,2400.0,Bhavya,Bengaluru,27,Silver
4,3103.0,103,Keyboard,3.0,1200.0,Cancelled,3600.0,Charan,Chennai,22,Bronze

In [21]:
outer_df = pd.merge(
    orders, customers,
    on="Customer_ID",
    how="outer"
)
outer_df.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership
0,3101.0,101,Laptop,1.0,55000.0,Delivered,55000.0,Anil,Hyderabad,24.0,Gold
1,3106.0,101,Laptop,1.0,55000.0,Returned,55000.0,Anil,Hyderabad,24.0,Gold
2,3102.0,102,Mouse,2.0,700.0,Delivered,1400.0,Bhavya,Bengaluru,27.0,Silver
3,3111.0,102,Keyboard,2.0,1200.0,Delivered,2400.0,Bhavya,Bengaluru,27.0,Silver
4,3103.0,103,Keyboard,3.0,1200.0,Cancelled,3600.0,Charan,Chennai,22.0,Bronze

In [22]:
result = pd.merge(
    orders,
    customers[["Customer_ID", "Customer_Name", "City"]],
    on="Customer_ID",
    how="left"
)
result.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City
0,3101,101,Laptop,1,55000,Delivered,55000,Anil,Hyderabad
1,3102,102,Mouse,2,700,Delivered,1400,Bhavya,Bengaluru
2,3103,103,Keyboard,3,1200,Cancelled,3600,Charan,Chennai
3,3104,104,Monitor,1,14000,Delivered,14000,Divya,Hyderabad
4,3105,105,Mouse,4,700,Delivered,2800,Esha,Vijayawada

In [25]:
orders_copy = orders.rename(
    columns={"Customer_ID": "Order_Customer_ID"})

result = pd.merge(
    orders_copy,
    customers,
    left_on="Order_Customer_ID",
    right_on="Customer_ID",
    how="inner")
result.head()

,Order_ID,Order_Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_ID,Customer_Name,City,Age,Membership
0,3101,101,Laptop,1,55000,Delivered,55000,101,Anil,Hyderabad,24,Gold
1,3102,102,Mouse,2,700,Delivered,1400,102,Bhavya,Bengaluru,27,Silver
2,3103,103,Keyboard,3,1200,Cancelled,3600,103,Charan,Chennai,22,Bronze
3,3104,104,Monitor,1,14000,Delivered,14000,104,Divya,Hyderabad,25,Gold
4,3105,105,Mouse,4,700,Delivered,2800,105,Esha,Vijayawada,29,Silver

In [26]:
product_result = pd.merge(
    orders,
    products,
    on="Product",
    how="left")
product_result.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Product_Category,Supplier
0,3101,101,Laptop,1,55000,Delivered,55000,Electronics,TechWorld
1,3102,102,Mouse,2,700,Delivered,1400,Accessories,GadgetHub
2,3103,103,Keyboard,3,1200,Cancelled,3600,Accessories,KeyPro
3,3104,104,Monitor,1,14000,Delivered,14000,Electronics,ViewMax
4,3105,105,Mouse,4,700,Delivered,2800,Accessories,GadgetHub

In [27]:
result = pd.merge(
    orders, customers,
    on="Customer_ID",
    how="left"
)

result = pd.merge(
    result, products,
    on="Product",
    how="left"
)

result.head()

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership,Product_Category,Supplier
0,3101,101,Laptop,1,55000,Delivered,55000,Anil,Hyderabad,24.0,Gold,Electronics,TechWorld
1,3102,102,Mouse,2,700,Delivered,1400,Bhavya,Bengaluru,27.0,Silver,Accessories,GadgetHub
2,3103,103,Keyboard,3,1200,Cancelled,3600,Charan,Chennai,22.0,Bronze,Accessories,KeyPro
3,3104,104,Monitor,1,14000,Delivered,14000,Divya,Hyderabad,25.0,Gold,Electronics,ViewMax
4,3105,105,Mouse,4,700,Delivered,2800,Esha,Vijayawada,29.0,Silver,Accessories,GadgetHub

In [28]:
result = pd.merge(
    orders, customers,
    on="Customer_ID",
    how="left",
    indicator=True
)

result[result["_merge"] == "left_only"]

,Order_ID,Customer_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Customer_Name,City,Age,Membership,_merge
18,3119,116,Mouse,5,700,Delivered,3500,NaN,NaN,NaN,NaN,left_only
19,3120,117,Keyboard,2,1200,Cancelled,2400,NaN,NaN,NaN,NaN,left_only

In [29]:
result = pd.merge(
    customers, orders,
    on="Customer_ID",
    how="left",
    indicator=True)

result[result["_merge"] == "left_only"]

,Customer_ID,Customer_Name,City,Age,Membership,Order_ID,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,_merge
18,118,Ravi,Hyderabad,32,Bronze,NaN,NaN,NaN,NaN,NaN,NaN,left_only