In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day22_retail_sorting.csv")

In [4]:
df.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
0,1001,Sandeep,Hyderabad,Laptop,Electronics,1,55000,Delivered,2026-03-01,55000
1,1002,Ravi,Bengaluru,Mouse,Accessories,2,800,Delivered,2026-03-02,1600
2,1003,Priya,Chennai,Monitor,Electronics,1,12500,Returned,2026-03-03,12500
3,1004,Anil,Pune,Keyboard,Accessories,1,1500,Delivered,2026-03-04,1500
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000

In [6]:
df.shape

(30, 10)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        30 non-null     int64
 1   Customer_Name   30 non-null     object
 2   City            30 non-null     object
 3   Product         30 non-null     object
 4   Category        30 non-null     object
 5   Quantity        30 non-null     int64
 6   Unit_Price_INR  30 non-null     int64
 7   Order_Status    30 non-null     object
 8   Order_Date      30 non-null     object
 9   Revenue_INR     30 non-null     int64
dtypes: int64(4), object(6)
memory usage: 2.5+ KB

In [9]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Order_Status      0
Order_Date        0
Revenue_INR       0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['Order_ID', 'Customer_Name', 'City', 'Product', 'Category', 'Quantity',
       'Unit_Price_INR', 'Order_Status', 'Order_Date', 'Revenue_INR'],
      dtype='object')

In [12]:
df.describe()

          Order_ID   Quantity  Unit_Price_INR   Revenue_INR
count    30.000000  30.000000       30.000000     30.000000
mean   1015.500000   1.666667    25200.000000  26551.666667
std       8.803408   1.028334    27061.969116  26297.969252
min    1001.000000   1.000000      650.000000   1500.000000
25%    1008.250000   1.000000     1412.500000   2825.000000
50%    1015.500000   1.000000    12250.000000  12750.000000
75%    1022.750000   2.000000    57750.000000  57750.000000
max    1030.000000   5.000000    64000.000000  64000.000000

In [15]:
df.sort_values(by="Customer_Name").head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
20,1021,Ajay,Hyderabad,Monitor,Electronics,1,11500,Delivered,2026-03-21,11500
3,1004,Anil,Pune,Keyboard,Accessories,1,1500,Delivered,2026-03-04,1500
7,1008,Arjun,Pune,Laptop,Electronics,1,58000,Delivered,2026-03-08,58000
15,1016,Asha,Pune,Monitor,Electronics,2,12000,Delivered,2026-03-16,24000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500

In [17]:
df.sort_values(by="Unit_Price_INR").head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
16,1017,Naveen,Hyderabad,Mouse,Accessories,5,650,Delivered,2026-03-17,3250
11,1012,Vijay,Pune,Mouse,Accessories,4,700,Cancelled,2026-03-12,2800
6,1007,Meena,Chennai,Mouse,Accessories,3,750,Delivered,2026-03-07,2250
1,1002,Ravi,Bengaluru,Mouse,Accessories,2,800,Delivered,2026-03-02,1600
26,1027,Mounika,Chennai,Mouse,Accessories,3,850,Delivered,2026-03-27,2550

In [19]:
df.sort_values(by="Unit_Price_INR",ascending=False).head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000
22,1023,Chandu,Chennai,Laptop,Electronics,1,61000,Delivered,2026-03-23,61000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500

In [20]:
df.sort_values(by="Revenue_INR",ascending=False).head(5)

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000
22,1023,Chandu,Chennai,Laptop,Electronics,1,61000,Delivered,2026-03-23,61000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500

In [22]:
df.sort_values(by=["City", "Unit_Price_INR"],ascending=[True, False]).head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500
9,1010,Rahul,Bengaluru,Laptop,Electronics,1,60000,Delivered,2026-03-10,60000
25,1026,Teja,Bengaluru,Monitor,Electronics,1,12700,Cancelled,2026-03-26,12700
5,1006,Kiran,Bengaluru,Monitor,Electronics,2,11800,Delivered,2026-03-06,23600

In [24]:
df.sort_values(by="Quantity",ascending=False)[["Product", "Quantity", "Revenue_INR"]].head()

     Product  Quantity  Revenue_INR
16     Mouse         5         3250
11     Mouse         4         2800
18  Keyboard         3         4050
26     Mouse         3         2550
6      Mouse         3         2250

In [26]:
df.sort_values(
    by="Order_Date",
    ascending=False).head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500
28,1029,Nikhil,Hyderabad,Keyboard,Accessories,1,1550,Delivered,2026-03-29,1550
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
26,1027,Mounika,Chennai,Mouse,Accessories,3,850,Delivered,2026-03-27,2550
25,1026,Teja,Bengaluru,Monitor,Electronics,1,12700,Cancelled,2026-03-26,12700

In [29]:
sorted_df = df.sort_values(by="Revenue_INR",ascending=False)
sorted_df.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000
22,1023,Chandu,Chennai,Laptop,Electronics,1,61000,Delivered,2026-03-23,61000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500

# sort_index() — Sort by index
- sort_values() sorts using column values. sort_index() sorts using row or column index labels.

In [31]:
# Sort rows by index
df.sort_index(ascending=True).head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
0,1001,Sandeep,Hyderabad,Laptop,Electronics,1,55000,Delivered,2026-03-01,55000
1,1002,Ravi,Bengaluru,Mouse,Accessories,2,800,Delivered,2026-03-02,1600
2,1003,Priya,Chennai,Monitor,Electronics,1,12500,Returned,2026-03-03,12500
3,1004,Anil,Pune,Keyboard,Accessories,1,1500,Delivered,2026-03-04,1500
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000

In [32]:
# Reverse row-index order
df.sort_index(ascending=False).head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500
28,1029,Nikhil,Hyderabad,Keyboard,Accessories,1,1550,Delivered,2026-03-29,1550
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
26,1027,Mounika,Chennai,Mouse,Accessories,3,850,Delivered,2026-03-27,2550
25,1026,Teja,Bengaluru,Monitor,Electronics,1,12700,Cancelled,2026-03-26,12700

In [33]:
df.sort_index(axis=1)

,Category,City,Customer_Name,Order_Date,Order_ID,Order_Status,Product,Quantity,Revenue_INR,Unit_Price_INR
0,Electronics,Hyderabad,Sandeep,2026-03-01,1001,Delivered,Laptop,1,55000,55000
1,Accessories,Bengaluru,Ravi,2026-03-02,1002,Delivered,Mouse,2,1600,800
2,Electronics,Chennai,Priya,2026-03-03,1003,Returned,Monitor,1,12500,12500
3,Accessories,Pune,Anil,2026-03-04,1004,Delivered,Keyboard,1,1500,1500
4,Electronics,Hyderabad,Divya,2026-03-05,1005,Cancelled,Laptop,1,62000,62000
5,Electronics,Bengaluru,Kiran,2026-03-06,1006,Delivered,Monitor,2,23600,11800
6,Accessories,Chennai,Meena,2026-03-07,1007,Delivered,Mouse,3,2250,750
7,Electronics,Pune,Arjun,2026-03-08,1008,Delivered,Laptop,1,58000,58000
8,Accessories,Hyderabad,Lakshmi,2026-03-09,1009,Returned,Keyboard,2,2800,1400
9,Electronics,Bengaluru,Rahul,2026-03-10,1010,Delivered,Laptop,1,60000,60000
10,Electronics,Chennai,Sneha,2026-03-11,1011,Delivered,Monitor,1,13200,13200
11,Accessories,Pune,Vijay,2026-03-12,1012,Cancelled,Mouse,4,2800,700
12,Electronics,Hyderabad,Pooja,2026-03-13,1013,Delivered,Monitor,1,12800,12800
13,Accessories,Bengaluru,Manoj,2026-03-14,1014,Delivered,Keyboard,2,3200,1600
14,Electronics,Chennai,Harsha,2026-03-15,1015,Returned,Laptop,1,57000,57000
15,Electronics,Pune,Asha,2026-03-16,1016,Delivered,Monitor,2,24000,12000
16,Accessories,Hyderabad,Naveen,2026-03-17,1017,Delivered,Mouse,5,3250,650
17,Electronics,Bengaluru,Geetha,2026-03-18,1018,Delivered,Laptop,1,64000,64000
18,Accessories,Chennai,Ramesh,2026-03-19,1019,Delivered,Keyboard,3,4050,1350
19,Electronics,Pune,Swathi,2026-03-20,1020,Cancelled,Laptop,1,59000,59000
20,Electronics,Hyderabad,Ajay,2026-03-21,1021,Delivered,Monitor,1,11500,11500
21,Accessories,Bengaluru,Kavya,2026-03-22,1022,Returned,Mouse,2,1800,900
22,Electronics,Chennai,Chandu,2026-03-23,1023,Delivered,Laptop,1,61000,61000
23,Accessories,Pune,Deepa,2026-03-24,1024,Delivered,Keyboard,2,2900,1450
24,Electronics,Hyderabad,Rohit,2026-03-25,1025,Delivered,Laptop,1,56500,56500
25,Electronics,Bengaluru,Teja,2026-03-26,1026,Cancelled,Monitor,1,12700,12700
26,Accessories,Chennai,Mounika,2026-03-27,1027,Delivered,Mouse,3,2550,850
27,Electronics,Pune,Sai,2026-03-28,1028,Delivered,Laptop,1,63000,63000
28,Accessories,Hyderabad,Nikhil,2026-03-29,1029,Delivered,Keyboard,1,1550,1550
29,Electronics,Bengaluru,Bhavya,2026-03-30,1030,Delivered,Laptop,1,60500,60500

# nlargest() and nsmallest()
- These are convenient shortcuts when you need only the top or bottom values.

In [35]:
# Top 5 highest-revenue orders
df.nlargest(5, "Revenue_INR")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000
22,1023,Chandu,Chennai,Laptop,Electronics,1,61000,Delivered,2026-03-23,61000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500

In [36]:
# 5 lowest-priced orders
df.nsmallest(5, "Unit_Price_INR")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
16,1017,Naveen,Hyderabad,Mouse,Accessories,5,650,Delivered,2026-03-17,3250
11,1012,Vijay,Pune,Mouse,Accessories,4,700,Cancelled,2026-03-12,2800
6,1007,Meena,Chennai,Mouse,Accessories,3,750,Delivered,2026-03-07,2250
1,1002,Ravi,Bengaluru,Mouse,Accessories,2,800,Delivered,2026-03-02,1600
26,1027,Mounika,Chennai,Mouse,Accessories,3,850,Delivered,2026-03-27,2550

# Handle ties and missing values

In [38]:
# Highest price first; break ties by product name
df.sort_values(
    by=["Unit_Price_INR", "Product"],
    ascending=[False, True])

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000
22,1023,Chandu,Chennai,Laptop,Electronics,1,61000,Delivered,2026-03-23,61000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500
9,1010,Rahul,Bengaluru,Laptop,Electronics,1,60000,Delivered,2026-03-10,60000
19,1020,Swathi,Pune,Laptop,Electronics,1,59000,Cancelled,2026-03-20,59000
7,1008,Arjun,Pune,Laptop,Electronics,1,58000,Delivered,2026-03-08,58000
14,1015,Harsha,Chennai,Laptop,Electronics,1,57000,Returned,2026-03-15,57000
24,1025,Rohit,Hyderabad,Laptop,Electronics,1,56500,Delivered,2026-03-25,56500
0,1001,Sandeep,Hyderabad,Laptop,Electronics,1,55000,Delivered,2026-03-01,55000
10,1011,Sneha,Chennai,Monitor,Electronics,1,13200,Delivered,2026-03-11,13200
12,1013,Pooja,Hyderabad,Monitor,Electronics,1,12800,Delivered,2026-03-13,12800
25,1026,Teja,Bengaluru,Monitor,Electronics,1,12700,Cancelled,2026-03-26,12700
2,1003,Priya,Chennai,Monitor,Electronics,1,12500,Returned,2026-03-03,12500
15,1016,Asha,Pune,Monitor,Electronics,2,12000,Delivered,2026-03-16,24000
5,1006,Kiran,Bengaluru,Monitor,Electronics,2,11800,Delivered,2026-03-06,23600
20,1021,Ajay,Hyderabad,Monitor,Electronics,1,11500,Delivered,2026-03-21,11500
13,1014,Manoj,Bengaluru,Keyboard,Accessories,2,1600,Delivered,2026-03-14,3200
28,1029,Nikhil,Hyderabad,Keyboard,Accessories,1,1550,Delivered,2026-03-29,1550
3,1004,Anil,Pune,Keyboard,Accessories,1,1500,Delivered,2026-03-04,1500
23,1024,Deepa,Pune,Keyboard,Accessories,2,1450,Delivered,2026-03-24,2900
8,1009,Lakshmi,Hyderabad,Keyboard,Accessories,2,1400,Returned,2026-03-09,2800
18,1019,Ramesh,Chennai,Keyboard,Accessories,3,1350,Delivered,2026-03-19,4050
21,1022,Kavya,Bengaluru,Mouse,Accessories,2,900,Returned,2026-03-22,1800
26,1027,Mounika,Chennai,Mouse,Accessories,3,850,Delivered,2026-03-27,2550
1,1002,Ravi,Bengaluru,Mouse,Accessories,2,800,Delivered,2026-03-02,1600
6,1007,Meena,Chennai,Mouse,Accessories,3,750,Delivered,2026-03-07,2250
11,1012,Vijay,Pune,Mouse,Accessories,4,700,Cancelled,2026-03-12,2800
16,1017,Naveen,Hyderabad,Mouse,Accessories,5,650,Delivered,2026-03-17,3250

In [39]:
# Put missing prices at the end
df.sort_values(
    by="Unit_Price_INR",
    na_position="last")

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Order_Date,Revenue_INR
16,1017,Naveen,Hyderabad,Mouse,Accessories,5,650,Delivered,2026-03-17,3250
11,1012,Vijay,Pune,Mouse,Accessories,4,700,Cancelled,2026-03-12,2800
6,1007,Meena,Chennai,Mouse,Accessories,3,750,Delivered,2026-03-07,2250
1,1002,Ravi,Bengaluru,Mouse,Accessories,2,800,Delivered,2026-03-02,1600
26,1027,Mounika,Chennai,Mouse,Accessories,3,850,Delivered,2026-03-27,2550
21,1022,Kavya,Bengaluru,Mouse,Accessories,2,900,Returned,2026-03-22,1800
18,1019,Ramesh,Chennai,Keyboard,Accessories,3,1350,Delivered,2026-03-19,4050
8,1009,Lakshmi,Hyderabad,Keyboard,Accessories,2,1400,Returned,2026-03-09,2800
23,1024,Deepa,Pune,Keyboard,Accessories,2,1450,Delivered,2026-03-24,2900
3,1004,Anil,Pune,Keyboard,Accessories,1,1500,Delivered,2026-03-04,1500
28,1029,Nikhil,Hyderabad,Keyboard,Accessories,1,1550,Delivered,2026-03-29,1550
13,1014,Manoj,Bengaluru,Keyboard,Accessories,2,1600,Delivered,2026-03-14,3200
20,1021,Ajay,Hyderabad,Monitor,Electronics,1,11500,Delivered,2026-03-21,11500
5,1006,Kiran,Bengaluru,Monitor,Electronics,2,11800,Delivered,2026-03-06,23600
15,1016,Asha,Pune,Monitor,Electronics,2,12000,Delivered,2026-03-16,24000
2,1003,Priya,Chennai,Monitor,Electronics,1,12500,Returned,2026-03-03,12500
25,1026,Teja,Bengaluru,Monitor,Electronics,1,12700,Cancelled,2026-03-26,12700
12,1013,Pooja,Hyderabad,Monitor,Electronics,1,12800,Delivered,2026-03-13,12800
10,1011,Sneha,Chennai,Monitor,Electronics,1,13200,Delivered,2026-03-11,13200
0,1001,Sandeep,Hyderabad,Laptop,Electronics,1,55000,Delivered,2026-03-01,55000
24,1025,Rohit,Hyderabad,Laptop,Electronics,1,56500,Delivered,2026-03-25,56500
14,1015,Harsha,Chennai,Laptop,Electronics,1,57000,Returned,2026-03-15,57000
7,1008,Arjun,Pune,Laptop,Electronics,1,58000,Delivered,2026-03-08,58000
19,1020,Swathi,Pune,Laptop,Electronics,1,59000,Cancelled,2026-03-20,59000
9,1010,Rahul,Bengaluru,Laptop,Electronics,1,60000,Delivered,2026-03-10,60000
29,1030,Bhavya,Bengaluru,Laptop,Electronics,1,60500,Delivered,2026-03-30,60500
22,1023,Chandu,Chennai,Laptop,Electronics,1,61000,Delivered,2026-03-23,61000
4,1005,Divya,Hyderabad,Laptop,Electronics,1,62000,Cancelled,2026-03-05,62000
27,1028,Sai,Pune,Laptop,Electronics,1,63000,Delivered,2026-03-28,63000
17,1018,Geetha,Bengaluru,Laptop,Electronics,1,64000,Delivered,2026-03-18,64000