# What are Apply, Map and Lambda?
- apply(): --Applies a function to a Series or DataFrame
- map()	: -- Maps values in a Series using a function or dictionary
- lambda :--Creates a small anonymous function

In [34]:
import pandas as pd
import numpy as np

In [35]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day33_pandas_apply_lambda.csv")

In [36]:
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City
0,3301,anil,sales,1,22000,3.2,92,Hyderabad
1,3302,BHAVYA,IT,3,45000,4.1,96,Bengaluru
2,3303,charan,hr,5,52000,3.8,88,Chennai
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad
4,3305,ESHA,sales,4,38000,3.5,90,Vijayawada

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         30 non-null     int64
 1   Employee_Name       30 non-null     object
 2   Department          30 non-null     object
 3   Experience_Years    30 non-null     int64
 4   Monthly_Salary_INR  30 non-null     int64
 5   Performance_Score   30 non-null     float64
 6   Attendance_Percent  30 non-null     int64
 7   City                30 non-null     object
dtypes: float64(1), int64(4), object(3)
memory usage: 2.0+ KB

In [38]:
df.shape

(30, 8)

In [39]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Experience_Years',
       'Monthly_Salary_INR', 'Performance_Score', 'Attendance_Percent',
       'City'],
      dtype='object')

In [40]:
df.describe()

,Employee_ID,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,3315.500000,4.033333,49200.000000,3.963333,92.733333
std,8.803408,2.326509,19492.527304,0.628892,4.841867
min,3301.000000,1.000000,22000.000000,2.800000,83.000000
25%,3308.250000,2.000000,33500.000000,3.425000,89.250000
50%,3315.500000,4.000000,45500.000000,4.050000,93.500000
75%,3322.750000,5.750000,63750.000000,4.500000,97.000000
max,3330.000000,9.000000,90000.000000,4.900000,99.000000

In [41]:
df.size

240

In [42]:
df["Department"].value_counts()

Department
IT         8
HR         6
sales      5
Finance    5
Sales      3
finance    2
hr         1
Name: count, dtype: int64

In [43]:
df["City"].value_counts()

City
Hyderabad     9
Bengaluru     9
Chennai       8
Vijayawada    4
Name: count, dtype: int64

In [44]:
df.isnull().sum()

Employee_ID           0
Employee_Name         0
Department            0
Experience_Years      0
Monthly_Salary_INR    0
Performance_Score     0
Attendance_Percent    0
City                  0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
# Lambda
square = lambda x: x * x
print(square(5))  # 25

25

In [47]:
# Map
df["Department"].map({"sales": "Sales","IT": "Information Technology"}).head()

0                     Sales
1    Information Technology
2                       NaN
3                       NaN
4                     Sales
Name: Department, dtype: object

In [48]:
# # Apply
df["Monthly_Salary_INR"].apply(lambda x: x * 12)

0      264000
1      540000
2      624000
3      360000
4      456000
5      780000
6      300000
7     1020000
8      504000
9      420000
10     864000
11     576000
12     660000
13     336000
14    1080000
15     480000
16     384000
17     816000
18     552000
19     696000
20     288000
21     900000
22     468000
23     984000
24     396000
25     600000
26     840000
27     312000
28     720000
29     492000
Name: Monthly_Salary_INR, dtype: int64

In [49]:
square = lambda x: x ** 2

square(5)

25

In [50]:
# Add two numbers
add = lambda a, b: a + b#
add(10, 20)

30

In [51]:
# Example 3 — Check even or odd
check = lambda x: "Even" if x % 2 == 0 else "Odd"
check(10)

'Even'

In [52]:
# Example 4 — Find the largest number
maximum = lambda a, b: a if a > b else b
maximum(20, 30)

30

In [53]:
# Example 5 — Convert employee names to uppercase
df["Employee_Name"] = df["Employee_Name"].apply(
    lambda x: x.strip().title())

df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City
0,3301,Anil,sales,1,22000,3.2,92,Hyderabad
1,3302,Bhavya,IT,3,45000,4.1,96,Bengaluru
2,3303,Charan,hr,5,52000,3.8,88,Chennai
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad
4,3305,Esha,sales,4,38000,3.5,90,Vijayawada

In [54]:
# Example 6 — Annual salary calculation
df["Annual_Salary"] = df["Monthly_Salary_INR"].apply(
    lambda x: x * 12)
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary
0,3301,Anil,sales,1,22000,3.2,92,Hyderabad,264000
1,3302,Bhavya,IT,3,45000,4.1,96,Bengaluru,540000
2,3303,Charan,hr,5,52000,3.8,88,Chennai,624000
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000
4,3305,Esha,sales,4,38000,3.5,90,Vijayawada,456000

In [55]:
# Example 8 — Experience classification
df["Experience_Level"] = df["Experience_Years"].apply(
    lambda x: "Fresher" if x <= 1
    else "Mid-Level" if x <= 5
    else "Experienced")
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level
0,3301,Anil,sales,1,22000,3.2,92,Hyderabad,264000,Fresher
1,3302,Bhavya,IT,3,45000,4.1,96,Bengaluru,540000,Mid-Level
2,3303,Charan,hr,5,52000,3.8,88,Chennai,624000,Mid-Level
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level
4,3305,Esha,sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level

In [56]:
# Example 9 — Performance classification
df["Performance_Status"] = df["Performance_Score"].apply(
    lambda x: "Excellent" if x >= 4.5
    else "Good" if x >= 3.5
    else "Average")
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status
0,3301,Anil,sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average
1,3302,Bhavya,IT,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good
2,3303,Charan,hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent
4,3305,Esha,sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good

In [57]:
# Example 10 — Attendance classification
df["Attendance_Status"] = df["Attendance_Percent"].apply(
    lambda x: "Good" if x >= 90 else "Low")

In [58]:
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status,Attendance_Status
0,3301,Anil,sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average,Good
1,3302,Bhavya,IT,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good,Good
2,3303,Charan,hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good,Low
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent,Good
4,3305,Esha,sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good,Good

In [61]:
# Example 11 — Department name mapping
df["Department"] = df["Department"].str.strip().str.title()

df["Department_Name"] = df["Department"].map({
    "Sales": "Sales Department",
    "It": "Information Technology",
    "Hr": "Human Resources",
    "Finance": "Finance Department"
})
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status,Attendance_Status,Department_Name
0,3301,Anil,Sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average,Good,Sales Department
1,3302,Bhavya,It,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good,Good,Information Technology
2,3303,Charan,Hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good,Low,Human Resources
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent,Good,Finance Department
4,3305,Esha,Sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good,Good,Sales Department

In [63]:
# Example 12 — City mapping
df["City_Code"] = df["City"].map({
    "Hyderabad": "HYD",
    "Bengaluru": "BLR",
    "Chennai": "CHE",
    "Vijayawada": "VJA"})
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status,Attendance_Status,Department_Name,City_Code
0,3301,Anil,Sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average,Good,Sales Department,HYD
1,3302,Bhavya,It,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good,Good,Information Technology,BLR
2,3303,Charan,Hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good,Low,Human Resources,CHE
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent,Good,Finance Department,HYD
4,3305,Esha,Sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good,Good,Sales Department,VJA

In [67]:
# Example 13 — Performance score mapping
df["Performance_Label"] = df["Performance_Status"].map({
    "Excellent": "A",
    "Good": "B",
    "Average": "C"
})
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status,Attendance_Status,Department_Name,City_Code,Performance_Label
0,3301,Anil,Sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average,Good,Sales Department,HYD,C
1,3302,Bhavya,It,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good,Good,Information Technology,BLR,B
2,3303,Charan,Hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good,Low,Human Resources,CHE,B
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent,Good,Finance Department,HYD,A
4,3305,Esha,Sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good,Good,Sales Department,VJA,B

In [70]:
# Example 14 — Map experience level
df["Experience_Code"] = df["Experience_Level"].map({
    "Fresher": 1,
    "Mid-Level": 2,
    "Experienced": 3})
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status,Attendance_Status,Department_Name,City_Code,Performance_Label,Experience_Code
0,3301,Anil,Sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average,Good,Sales Department,HYD,C,1
1,3302,Bhavya,It,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good,Good,Information Technology,BLR,B,2
2,3303,Charan,Hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good,Low,Human Resources,CHE,B,2
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent,Good,Finance Department,HYD,A,2
4,3305,Esha,Sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good,Good,Sales Department,VJA,B,2

In [71]:
# Example 15 — Create salary category
df["Salary_Category"] = df["Monthly_Salary_INR"].apply(
    lambda x: "High" if x >= 60000
    else "Medium" if x >= 35000
    else "Low")

In [72]:
df.head()

,Employee_ID,Employee_Name,Department,Experience_Years,Monthly_Salary_INR,Performance_Score,Attendance_Percent,City,Annual_Salary,Experience_Level,Performance_Status,Attendance_Status,Department_Name,City_Code,Performance_Label,Experience_Code,Salary_Category
0,3301,Anil,Sales,1,22000,3.2,92,Hyderabad,264000,Fresher,Average,Good,Sales Department,HYD,C,1,Low
1,3302,Bhavya,It,3,45000,4.1,96,Bengaluru,540000,Mid-Level,Good,Good,Information Technology,BLR,B,2,Medium
2,3303,Charan,Hr,5,52000,3.8,88,Chennai,624000,Mid-Level,Good,Low,Human Resources,CHE,B,2,Medium
3,3304,Divya,Finance,2,30000,4.5,97,Hyderabad,360000,Mid-Level,Excellent,Good,Finance Department,HYD,A,2,Low
4,3305,Esha,Sales,4,38000,3.5,90,Vijayawada,456000,Mid-Level,Good,Good,Sales Department,VJA,B,2,Medium