# What is Crosstab?
- pd.crosstab() creates a frequency table that shows how often categories occur together.

# For example, a company manager wants to know:
- How many orders came from each city?
- How many orders are Delivered, Cancelled, or Returned?
- Which city has the most Delivered orders?

# Basic syntax:
pd.crosstab(
    index=df["City"],
    columns=df["Order_Status"]
)

- index — categories shown as rows.
- columns — categories shown as columns.
- By default, the table counts how many times each combination occurs.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day30_pandas_crosstab.csv")

In [4]:
df.head()

,Order_ID,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3001,Hyderabad,Laptop,Electronics,1,55000,Delivered,55000
1,3002,Bengaluru,Mouse,Accessories,3,700,Delivered,2100
2,3003,Chennai,Keyboard,Accessories,2,1200,Cancelled,2400
3,3004,Vijayawada,Monitor,Electronics,1,14000,Delivered,14000
4,3005,Hyderabad,Mouse,Accessories,4,700,Delivered,2800

In [5]:
df.shape

(30, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        30 non-null     int64
 1   City            30 non-null     object
 2   Product         30 non-null     object
 3   Category        30 non-null     object
 4   Quantity        30 non-null     int64
 5   Unit_Price_INR  30 non-null     int64
 6   Order_Status    30 non-null     object
 7   Revenue_INR     30 non-null     int64
dtypes: int64(4), object(4)
memory usage: 2.0+ KB

In [7]:
df.columns

Index(['Order_ID', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price_INR',
       'Order_Status', 'Revenue_INR'],
      dtype='object')

In [43]:
df["City"].value_counts()

City
Hyderabad     8
Bengaluru     8
Chennai       7
Vijayawada    7
Name: count, dtype: int64

In [44]:
df["Product"].value_counts()

Product
Mouse       9
Laptop      7
Keyboard    7
Monitor     7
Name: count, dtype: int64

In [45]:
df["Category"].value_counts()

Category
Accessories    16
Electronics    14
Name: count, dtype: int64

In [46]:
df["Product"].unique()

array(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], dtype=object)

In [47]:
df["City"].unique()

array(['Hyderabad', 'Bengaluru', 'Chennai', 'Vijayawada'], dtype=object)

In [48]:
df["Category"].unique()

array(['Electronics', 'Accessories'], dtype=object)

In [9]:
df.describe()

          Order_ID   Quantity  Unit_Price_INR    Revenue_INR
count    30.000000  30.000000        30.00000      30.000000
mean   3015.500000   2.200000     16590.00000   21233.333333
std       8.803408   1.297212     22209.54051   30684.224109
min    3001.000000   1.000000       700.00000    1400.000000
25%    3008.250000   1.000000       700.00000    2500.000000
50%    3015.500000   2.000000      1200.00000    4200.000000
75%    3022.750000   3.000000     14000.00000   14000.000000
max    3030.000000   5.000000     55000.00000  110000.000000

In [10]:
df.isnull().sum()

Order_ID          0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Order_Status      0
Revenue_INR       0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
# Orders by city
pd.crosstab(["City"],df["Order_Status"])

Order_Status  Cancelled  Delivered  Returned
row_0
City                  5         22         3

In [14]:
# Orders by product
pd.crosstab(["Product"],df["Order_Status"])

Order_Status  Cancelled  Delivered  Returned
row_0
Product               5         22         3

In [15]:
# Orders by category
pd.crosstab(["Category"],["Order_Status"])

col_0     Order_Status
row_0
Category             1

In [16]:
# Product count in each city
pd.crosstab(["City"],["Product"])

col_0  Product
row_0
City         1

In [17]:
# Category count in each city
pd.crosstab(["City"],["Category"])

col_0  Category
row_0
City          1

In [18]:
# Add row and column totals
pd.crosstab(df["City"],["Order_Status"],margins=True)

col_0       Order_Status  All
City
Bengaluru              8    8
Chennai                7    7
Hyderabad              8    8
Vijayawada             7    7
All                   30   30

- margins=True adds totals for each row and column.

In [20]:
# Add a custom total name
pd.crosstab(df["City"],df["Order_Status"],margins=True,margins_name="Grand Total")

Order_Status  Cancelled  Delivered  Returned  Grand Total
City
Bengaluru             1          6         1            8
Chennai               1          6         0            7
Hyderabad             2          5         1            8
Vijayawada            1          5         1            7
Grand Total           5         22         3           30

# Percentages and normalization

In [21]:
# Row-wise percentages
pd.crosstab(df["City"],df["Order_Status"],normalize="index").round(2) * 100

Order_Status  Cancelled  Delivered  Returned
City
Bengaluru          12.0       75.0      12.0
Chennai            14.0       86.0       0.0
Hyderabad          25.0       62.0      12.0
Vijayawada         14.0       71.0      14.0

- Shows the percentage distribution of order statuses within each city.

In [23]:
# Column-wise percentages
pd.crosstab(df["City"],df["Order_Status"],normalize="columns").round(2) * 100

Order_Status  Cancelled  Delivered  Returned
City
Bengaluru          20.0       27.0      33.0
Chennai            20.0       27.0       0.0
Hyderabad          40.0       23.0      33.0
Vijayawada         20.0       23.0      33.0

- Shows how each order status is distributed across cities.

In [27]:
# Overall percentages
pd.crosstab(df["City"],df["Order_Status"],normalize="all").round(3) * 100

Order_Status  Cancelled  Delivered  Returned
City
Bengaluru           3.3       20.0       3.3
Chennai             3.3       20.0       0.0
Hyderabad           6.7       16.7       3.3
Vijayawada          3.3       16.7       3.3

- Shows each city-status combination as a percentage of all rows.

In [30]:
# Count unique order IDs
pd.crosstab(
    df["City"],
    df["Order_Status"],
    values=df["Order_ID"],
    aggfunc="nunique").fillna(0).astype(int)

Order_Status  Cancelled  Delivered  Returned
City
Bengaluru             1          6         1
Chennai               1          6         0
Hyderabad             2          5         1
Vijayawada            1          5         1

In [31]:
# Total quantity by city and product
pd.crosstab(
    df["City"],
    df["Product"],
    values=df["Quantity"],
    aggfunc="sum"
).fillna(0)

Product     Keyboard  Laptop  Monitor  Mouse
City
Bengaluru        3.0     2.0      1.0   12.0
Chennai          6.0     5.0      0.0    2.0
Hyderabad        0.0     1.0      4.0   13.0
Vijayawada       9.0     1.0      2.0    5.0

In [33]:
# Total revenue by city and product
pd.crosstab(
    df["City"],
    df["Product"],
    values=df["Revenue_INR"],
    aggfunc="sum"
).fillna(0)

Product     Keyboard    Laptop  Monitor   Mouse
City
Bengaluru     3600.0  110000.0  14000.0  8400.0
Chennai       7200.0  275000.0      0.0  1400.0
Hyderabad        0.0   55000.0  56000.0  9100.0
Vijayawada   10800.0   55000.0  28000.0  3500.0

In [34]:
# Average revenue by city and product
pd.crosstab(
    df["City"],
    df["Product"],
    values=df["Revenue_INR"],
    aggfunc="mean"
).fillna(0)

Product     Keyboard        Laptop  Monitor        Mouse
City
Bengaluru     3600.0  55000.000000  14000.0  2100.000000
Chennai       2400.0  91666.666667      0.0  1400.000000
Hyderabad        0.0  55000.000000  14000.0  3033.333333
Vijayawada    3600.0  55000.000000  14000.0  3500.000000

In [36]:
# Maximum quantity by city and product
pd.crosstab(
    df["City"],
    df["Product"],
    values=df["Quantity"],
    aggfunc="max"
).fillna(0)

Product     Keyboard  Laptop  Monitor  Mouse
City
Bengaluru        3.0     1.0      1.0    4.0
Chennai          2.0     2.0      0.0    2.0
Hyderabad        0.0     1.0      1.0    5.0
Vijayawada       4.0     1.0      1.0    5.0

In [38]:
# City and category with totals
pd.crosstab(
    df["City"],
    df["Category"],
    margins=True,
     margins_name="Total"
)

Category    Accessories  Electronics  Total
City
Bengaluru             5            3      8
Chennai               4            3      7
Hyderabad             3            5      8
Vijayawada            4            3      7
Total                16           14     30

In [39]:
# Product and order status with totals
pd.crosstab(df["Product"],df["Order_Status"],margins=True)

Order_Status  Cancelled  Delivered  Returned  All
Product
Keyboard              2          5         0    7
Laptop                1          4         2    7
Monitor               2          4         1    7
Mouse                 0          9         0    9
All                   5         22         3   30

In [40]:
# Count each category by city, normalized
pd.crosstab(
    df["City"],
    df["Category"],
    normalize="index").round(2) * 100

Category    Accessories  Electronics
City
Bengaluru          62.0         38.0
Chennai            57.0         43.0
Hyderabad          38.0         62.0
Vijayawada         57.0         43.0

In [41]:
# 9 — Filter Delivered orders and count products by city
delivered = df[df["Order_Status"] == "Delivered"]
pd.crosstab(
    delivered["City"],
    delivered["Product"],
    margins=True)

Product     Keyboard  Laptop  Monitor  Mouse  All
City
Bengaluru          1       0        1      4    6
Chennai            2       3        0      1    6
Hyderabad          0       1        1      3    5
Vijayawada         2       0        2      1    5
All                5       4        4      9   22

In [42]:
# Create a city-wise order status report
status_report = pd.crosstab(
    index=df["City"],
    columns=df["Order_Status"],
    margins=True,
    margins_name="Total")

status_report

Order_Status  Cancelled  Delivered  Returned  Total
City
Bengaluru             1          6         1      8
Chennai               1          6         0      7
Hyderabad             2          5         1      8
Vijayawada            1          5         1      7
Total                 5         22         3     30