# What is a Pivot Table?
- A Pivot Table summarizes large amounts of data into a compact report.

In [16]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day29_pandas_pivot_tables.csv")

In [18]:
df.head()

,Order_ID,City,Product,Category,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,2901,Hyderabad,Laptop,Electronics,1,55000,Delivered,55000
1,2902,Bengaluru,Mouse,Accessories,3,700,Delivered,2100
2,2903,Chennai,Keyboard,Accessories,2,1200,Cancelled,2400
3,2904,Vijayawada,Monitor,Electronics,1,14000,Delivered,14000
4,2905,Hyderabad,Mouse,Accessories,4,700,Delivered,2800

In [19]:
df.shape

(30, 8)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        30 non-null     int64
 1   City            30 non-null     object
 2   Product         30 non-null     object
 3   Category        30 non-null     object
 4   Quantity        30 non-null     int64
 5   Unit_Price_INR  30 non-null     int64
 6   Order_Status    30 non-null     object
 7   Revenue_INR     30 non-null     int64
dtypes: int64(4), object(4)
memory usage: 2.0+ KB

In [21]:
df.columns

Index(['Order_ID', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price_INR',
       'Order_Status', 'Revenue_INR'],
      dtype='object')

In [22]:
df.size

240

In [23]:
df.describe()

          Order_ID   Quantity  Unit_Price_INR    Revenue_INR
count    30.000000  30.000000        30.00000      30.000000
mean   2915.500000   2.200000     16590.00000   21233.333333
std       8.803408   1.297212     22209.54051   30684.224109
min    2901.000000   1.000000       700.00000    1400.000000
25%    2908.250000   1.000000       700.00000    2500.000000
50%    2915.500000   2.000000      1200.00000    4200.000000
75%    2922.750000   3.000000     14000.00000   14000.000000
max    2930.000000   5.000000     55000.00000  110000.000000

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

Order_ID          0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Order_Status      0
Revenue_INR       0
dtype: int64

In [26]:
df["Product"].value_counts()

Product
Mouse       9
Laptop      7
Keyboard    7
Monitor     7
Name: count, dtype: int64

# Basic Pivot Table Syntax

In [27]:
pd.pivot_table(
    df,
    values="Revenue_INR",
    index="City",
    aggfunc="sum"
)

            Revenue_INR
City
Bengaluru        136000
Chennai          283600
Hyderabad        120100
Vijayawada        97300

- values— Which column should be calculated?
- index— Which column form the rows?
- columns— Which column form separate columns?
- aggfunc— What calculation should be performed?
- fill_value— What value should replace combination mistakes?

In [29]:
# Total Revenue by City
total_revenue=pd.pivot_table(df,
                            values="Revenue_INR",
                            index="City",
                            aggfunc="sum")
total_revenue

            Revenue_INR
City
Bengaluru        136000
Chennai          283600
Hyderabad        120100
Vijayawada        97300

In [31]:
# Average revenue by city
avg_revenue=pd.pivot_table(df,
                          values="Revenue_INR",
                          index="City",
                          aggfunc="mean")
avg_revenue

             Revenue_INR
City
Bengaluru   17000.000000
Chennai     40514.285714
Hyderabad   15012.500000
Vijayawada  13900.000000

In [34]:
# Total quantity by product
total=pd.pivot_table(df,
                    values="Quantity",
                    index="Product",
                    aggfunc="sum")
total_revenue

            Revenue_INR
City
Bengaluru        136000
Chennai          283600
Hyderabad        120100
Vijayawada        97300

In [36]:
# Average Price by Product
avg_price=pd.pivot_table(df,
                        values="Unit_Price_INR",
                        index="Product",
                        aggfunc="sum")
avg_price

          Unit_Price_INR
Product
Keyboard            8400
Laptop            385000
Monitor            98000
Mouse               6300

In [38]:
# Order Count by City
count_order=pd.pivot_table(df,
                          values="Order_ID",
                          index="City",
                          aggfunc="count")
count_order

            Order_ID
City
Bengaluru          8
Chennai            7
Hyderabad          8
Vijayawada         7

In [42]:
# Revenue by City and Product
pd.pivot_table(df,
              values="Revenue_INR",
              index="City",
              columns="Product",
              aggfunc="sum",
              fill_value=0)

Product     Keyboard  Laptop  Monitor  Mouse
City
Bengaluru       3600  110000    14000   8400
Chennai         7200  275000        0   1400
Hyderabad          0   55000    56000   9100
Vijayawada     10800   55000    28000   3500

In [44]:
# Quantity by City and Product
pd.pivot_table(df,
              values="Quantity",
              index="City",
              columns="Product",
              aggfunc="sum",
              fill_value=0)

Product     Keyboard  Laptop  Monitor  Mouse
City
Bengaluru          3       2        1     12
Chennai            6       5        0      2
Hyderabad          0       1        4     13
Vijayawada         9       1        2      5

In [45]:
# Order Count by City and Status
pd.pivot_table(df,
              values="Order_ID",
              index="City",
              columns="Order_Status",
              aggfunc="count",
              fill_value=0)

Order_Status  Cancelled  Delivered  Returned
City
Bengaluru             1          6         1
Chennai               1          6         0
Hyderabad             2          5         1
Vijayawada            1          5         1

In [46]:
# Revenue by category and city
pd.pivot_table(df,
              values="Revenue_INR",
              index="City",
              columns="Category",
              aggfunc="sum",
              fill_value=0)

Category    Accessories  Electronics
City
Bengaluru         12000       124000
Chennai            8600       275000
Hyderabad          9100       111000
Vijayawada        14300        83000

In [47]:
# Quantity by Product and Status
pd.pivot_table(df,
              values="Quantity",
              index="Product",
              columns="Order_Status",
              aggfunc="sum",
              fill_value=0)

Order_Status  Cancelled  Delivered  Returned
Product
Keyboard              6         12         0
Laptop                1          6         2
Monitor               2          4         1
Mouse                 0         32         0

In [48]:
# Total and average revenue by city
pd.pivot_table(df,
              values="Revenue_INR",
              index="City",
              aggfunc=["mean","sum"])

                    mean         sum
             Revenue_INR Revenue_INR
City
Bengaluru   17000.000000      136000
Chennai     40514.285714      283600
Hyderabad   15012.500000      120100
Vijayawada  13900.000000       97300

In [49]:
# Multiple Calculations by Product
pd.pivot_table(
    df,
    values=["Quantity", "Revenue_INR"],
    index="Product",
    aggfunc={
        "Quantity": "sum",
        "Revenue_INR": ["sum", "mean"]})

         Quantity   Revenue_INR
              sum          mean     sum
Product
Keyboard       18   3085.714286   21600
Laptop          9  70714.285714  495000
Monitor         7  14000.000000   98000
Mouse          32   2488.888889   22400

In [50]:
# Revenue and quantity by city and product
pd.pivot_table(
    df,
    values=["Revenue_INR", "Quantity"],
    index="City",
    columns="Product",
    aggfunc="sum",
    fill_value=0)

           Quantity                      Revenue_INR
Product    Keyboard Laptop Monitor Mouse    Keyboard  Laptop Monitor Mouse
City
Bengaluru         3      2       1    12        3600  110000   14000  8400
Chennai           6      5       0     2        7200  275000       0  1400
Hyderabad         0      1       4    13           0   55000   56000  9100
Vijayawada        9      1       2     5       10800   55000   28000  3500

In [51]:
# Average quantity by city and product
pd.pivot_table(
    df,
    values="Quantity",
    index="City",
    columns="Product",
    aggfunc="mean",
    fill_value=0)

Product     Keyboard    Laptop  Monitor     Mouse
City
Bengaluru        3.0  1.000000      1.0  3.000000
Chennai          2.0  1.666667      0.0  2.000000
Hyderabad        0.0  1.000000      1.0  4.333333
Vijayawada       3.0  1.000000      1.0  5.000000

In [52]:
# Count unique products by city
pd.pivot_table(
    df,
    values="Product",
    index="City",
    aggfunc="nunique")

            Product
City
Bengaluru         4
Chennai           3
Hyderabad         3
Vijayawada        4

In [53]:
# Maximum revenue by city
pd.pivot_table(
    df,
    values="Revenue_INR",
    index="City",
    aggfunc="max")

            Revenue_INR
City
Bengaluru         55000
Chennai          110000
Hyderabad         55000
Vijayawada        55000

In [54]:
# Minimum Product Price by Category
pd.pivot_table(
    df,
    values="Unit_Price_INR",
    index="Category",
    aggfunc="min")

             Unit_Price_INR
Category
Accessories             700
Electronics           14000

In [55]:
# Revenue by city, product and order status
pd.pivot_table(
    df,
    values="Revenue_INR",
    index=["City", "Product"],
    columns="Order_Status",
    aggfunc="sum",
    fill_value=0)

Order_Status         Cancelled  Delivered  Returned
City       Product
Bengaluru  Keyboard          0       3600         0
           Laptop        55000          0     55000
           Monitor           0      14000         0
           Mouse             0       8400         0
Chennai    Keyboard       2400       4800         0
           Laptop            0     275000         0
           Mouse             0       1400         0
Hyderabad  Laptop            0      55000         0
           Monitor       28000      14000     14000
           Mouse             0       9100         0
Vijayawada Keyboard       4800       6000         0
           Laptop            0          0     55000
           Monitor           0      28000         0
           Mouse             0       3500         0

In [56]:
# 19 — Add row and column fulls
pd.pivot_table(
    df,
    values="Revenue_INR",
    index="City",
    columns="Product",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="Grand Total")

Product      Keyboard  Laptop  Monitor  Mouse  Grand Total
City
Bengaluru        3600  110000    14000   8400       136000
Chennai          7200  275000        0   1400       283600
Hyderabad           0   55000    56000   9100       120100
Vijayawada      10800   55000    28000   3500        97300
Grand Total     21600  495000    98000  22400       637000

In [57]:
# 20 — Create a full sales summary
sales_pivot = pd.pivot_table(
    df,
    values=["Revenue_INR", "Quantity", "Order_ID"],
    index="City",
    columns="Category",
    aggfunc={
        "Revenue_INR": "sum",
        "Quantity": "sum",
        "Order_ID": "count"
    },
    fill_value=0)

sales_pivot

              Order_ID                Quantity             Revenue_INR  \
Category   Accessories Electronics Accessories Electronics Accessories
City
Bengaluru            5           3          15           3       12000
Chennai              4           3           8           5        8600
Hyderabad            3           5          13           5        9100
Vijayawada           4           3          14           3       14300


Category   Electronics
City
Bengaluru       124000
Chennai         275000
Hyderabad       111000
Vijayawada       83000