In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day17_retail_orders.csv")

In [6]:
df.head()

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
0,1001,2026-01-03,Ravi,Hyderabad,Laptop,Electronics,1.0,55000.0,UPI,Delivered,55000
1,1002,2026-01-04,Asha,Bengaluru,Mouse,Accessories,2.0,700.0,Credit Card,Delivered,1400
2,1003,2026-01-05,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200.0,UPI,Delivered,1200
3,1004,2026-01-06,Neha,Chennai,Laptop,Electronics,1.0,52000.0,Debit Card,Delivered,52000
4,1005,2026-01-07,NaN,Pune,Monitor,Electronics,2.0,15000.0,UPI,Cancelled,30000

In [7]:
df.head(3)

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
0,1001,2026-01-03,Ravi,Hyderabad,Laptop,Electronics,1.0,55000.0,UPI,Delivered,55000
1,1002,2026-01-04,Asha,Bengaluru,Mouse,Accessories,2.0,700.0,Credit Card,Delivered,1400
2,1003,2026-01-05,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200.0,UPI,Delivered,1200

In [8]:
# tail() — last five rows
df.tail()

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
15,1016,2026-01-18,Divya,Bengaluru,Monitor,Electronics,1.0,NaN,Credit Card,Returned,15500
16,1017,2026-01-19,Ravi,Hyderabad,Keyboard,Accessories,2.0,1150.0,Cash,Delivered,2300
17,1018,2026-01-20,Asha,Pune,Laptop,Electronics,1.0,57000.0,UPI,Delivered,57000
18,1019,2026-01-21,Kiran,Bengaluru,Mouse,Accessories,2.0,780.0,Debit Card,Delivered,1560
19,1020,2026-01-22,Sandeep,Chennai,Monitor,Electronics,1.0,14800.0,Credit Card,Cancelled,14800

In [10]:
df.tail(3)

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
17,1018,2026-01-20,Asha,Pune,Laptop,Electronics,1.0,57000.0,UPI,Delivered,57000
18,1019,2026-01-21,Kiran,Bengaluru,Mouse,Accessories,2.0,780.0,Debit Card,Delivered,1560
19,1020,2026-01-22,Sandeep,Chennai,Monitor,Electronics,1.0,14800.0,Credit Card,Cancelled,14800

In [11]:
# sample() — random rows
df.sample(5,random_state=42)

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
0,1001,2026-01-03,Ravi,Hyderabad,Laptop,Electronics,1.0,55000.0,UPI,Delivered,55000
17,1018,2026-01-20,Asha,Pune,Laptop,Electronics,1.0,57000.0,UPI,Delivered,57000
15,1016,2026-01-18,Divya,Bengaluru,Monitor,Electronics,1.0,NaN,Credit Card,Returned,15500
1,1002,2026-01-04,Asha,Bengaluru,Mouse,Accessories,2.0,700.0,Credit Card,Delivered,1400
8,1009,2026-01-11,Ravi,Pune,Monitor,Electronics,1.0,14500.0,NaN,Returned,14500

In [12]:
# # Number of rows and columns
df.shape

(20, 11)

In [13]:
# Column names
df.columns

Index(['Order_ID', 'Order_Date', 'Customer', 'City', 'Product', 'Category',
       'Quantity', 'Unit_Price_INR', 'Payment_Method', 'Order_Status',
       'Revenue_INR'],
      dtype='object')

In [15]:
# # Data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        20 non-null     int64
 1   Order_Date      20 non-null     object
 2   Customer        19 non-null     object
 3   City            20 non-null     object
 4   Product         20 non-null     object
 5   Category        20 non-null     object
 6   Quantity        19 non-null     float64
 7   Unit_Price_INR  19 non-null     float64
 8   Payment_Method  19 non-null     object
 9   Order_Status    20 non-null     object
 10  Revenue_INR     20 non-null     int64
dtypes: float64(2), int64(2), object(7)
memory usage: 1.8+ KB

In [16]:
# Statistical summary of numeric columns
df.describe()

         Order_ID   Quantity  Unit_Price_INR   Revenue_INR
count    20.00000  19.000000       19.000000     20.000000
mean   1010.50000   1.578947    20715.789474  21628.500000
std       5.91608   0.692483    24202.493057  23262.383748
min    1001.00000   1.000000      650.000000   1200.000000
25%    1005.75000   1.000000      940.000000   2107.500000
50%    1010.50000   1.000000    14000.000000  14250.000000
75%    1015.25000   2.000000    52500.000000  52250.000000
max    1020.00000   3.000000    57000.000000  57000.000000

In [18]:
# Data types of all columns
df.dtypes

Order_ID            int64
Order_Date         object
Customer           object
City               object
Product            object
Category           object
Quantity          float64
Unit_Price_INR    float64
Payment_Method     object
Order_Status       object
Revenue_INR         int64
dtype: object

In [38]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer          1
City              0
Product           0
Category          0
Quantity          1
Unit_Price_INR    1
Payment_Method    1
Order_Status      0
Revenue_INR       0
dtype: int64

In [42]:
df.drop_duplicates()

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
0,1001,2026-01-03,Ravi,Hyderabad,Laptop,Electronics,1.0,55000.0,UPI,Delivered,55000
1,1002,2026-01-04,Asha,Bengaluru,Mouse,Accessories,2.0,700.0,Credit Card,Delivered,1400
2,1003,2026-01-05,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200.0,UPI,Delivered,1200
3,1004,2026-01-06,Neha,Chennai,Laptop,Electronics,1.0,52000.0,Debit Card,Delivered,52000
4,1005,2026-01-07,NaN,Pune,Monitor,Electronics,2.0,15000.0,UPI,Cancelled,30000
5,1006,2026-01-08,Priya,Hyderabad,Mouse,Accessories,3.0,650.0,Cash,Delivered,1950
6,1007,2026-01-09,Arjun,Bengaluru,Laptop,Electronics,1.0,56000.0,Credit Card,Delivered,56000
7,1008,2026-01-10,Divya,Chennai,Keyboard,Accessories,2.0,1100.0,UPI,Delivered,2200
8,1009,2026-01-11,Ravi,Pune,Monitor,Electronics,1.0,14500.0,NaN,Returned,14500
9,1010,2026-01-12,Asha,Hyderabad,Laptop,Electronics,1.0,54000.0,UPI,Delivered,54000
10,1011,2026-01-13,Kiran,Chennai,Mouse,Accessories,2.0,750.0,Cash,Delivered,1500
11,1012,2026-01-14,Sandeep,Bengaluru,Monitor,Electronics,NaN,14000.0,Credit Card,Cancelled,14000
12,1013,2026-01-15,Neha,Hyderabad,Keyboard,Accessories,2.0,1250.0,UPI,Delivered,2500
13,1014,2026-01-16,Priya,Pune,Laptop,Electronics,1.0,53000.0,Debit Card,Delivered,53000
14,1015,2026-01-17,Arjun,Chennai,Mouse,Accessories,3.0,720.0,UPI,Delivered,2160
15,1016,2026-01-18,Divya,Bengaluru,Monitor,Electronics,1.0,NaN,Credit Card,Returned,15500
16,1017,2026-01-19,Ravi,Hyderabad,Keyboard,Accessories,2.0,1150.0,Cash,Delivered,2300
17,1018,2026-01-20,Asha,Pune,Laptop,Electronics,1.0,57000.0,UPI,Delivered,57000
18,1019,2026-01-21,Kiran,Bengaluru,Mouse,Accessories,2.0,780.0,Debit Card,Delivered,1560
19,1020,2026-01-22,Sandeep,Chennai,Monitor,Electronics,1.0,14800.0,Credit Card,Cancelled,14800

In [39]:
df.duplicated().sum()

np.int64(0)

# Select specific columns
- Suppose your manager asks for the customer names and cities.

In [43]:
df[["Customer","City"]].head()

  Customer       City
0     Ravi  Hyderabad
1     Asha  Bengaluru
2  Sandeep  Hyderabad
3     Neha    Chennai
4      NaN       Pune

In [23]:
df[["Order_ID", "Product", "Order_Status"]].head()

   Order_ID   Product Order_Status
0      1001    Laptop    Delivered
1      1002     Mouse    Delivered
2      1003  Keyboard    Delivered
3      1004    Laptop    Delivered
4      1005   Monitor    Cancelled

In [27]:
# Which orders were delivered?
delivered_orders = df[df["Order_Status"] == "Delivered"].head()
delivered_orders

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
0,1001,2026-01-03,Ravi,Hyderabad,Laptop,Electronics,1.0,55000.0,UPI,Delivered,55000
1,1002,2026-01-04,Asha,Bengaluru,Mouse,Accessories,2.0,700.0,Credit Card,Delivered,1400
2,1003,2026-01-05,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200.0,UPI,Delivered,1200
3,1004,2026-01-06,Neha,Chennai,Laptop,Electronics,1.0,52000.0,Debit Card,Delivered,52000
5,1006,2026-01-08,Priya,Hyderabad,Mouse,Accessories,3.0,650.0,Cash,Delivered,1950

In [28]:
# Which products cost more than ₹10,000?
expensive_products = df[df["Unit_Price_INR"] > 10000]
print(expensive_products[["Product", "Unit_Price_INR"]])

    Product  Unit_Price_INR
0    Laptop         55000.0
3    Laptop         52000.0
4   Monitor         15000.0
6    Laptop         56000.0
8   Monitor         14500.0
9    Laptop         54000.0
11  Monitor         14000.0
13   Laptop         53000.0
17   Laptop         57000.0
19  Monitor         14800.0

In [29]:
# How many orders came from each city?
df["City"].value_counts()

City
Hyderabad    6
Bengaluru    5
Chennai      5
Pune         4
Name: count, dtype: int64

In [30]:
# Which payment methods are used?
print(df["Payment_Method"].value_counts(dropna=False))

Payment_Method
UPI            8
Credit Card    5
Debit Card     3
Cash           3
NaN            1
Name: count, dtype: int64

In [31]:
# What is the average unit price?
print(df["Unit_Price_INR"].mean())

20715.78947368421

In [32]:
# What is the order status distribution?
print(df["Order_Status"].value_counts())

Order_Status
Delivered    15
Cancelled     3
Returned      2
Name: count, dtype: int64

In [33]:
# Missing values in each column
print(df.isnull().sum())

Order_ID          0
Order_Date        0
Customer          1
City              0
Product           0
Category          0
Quantity          1
Unit_Price_INR    1
Payment_Method    1
Order_Status      0
Revenue_INR       0
dtype: int64

In [34]:
df[df["Customer"].isnull()]

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
4,1005,2026-01-07,NaN,Pune,Monitor,Electronics,2.0,15000.0,UPI,Cancelled,30000

In [35]:
df[df["Unit_Price_INR"].isnull()]

,Order_ID,Order_Date,Customer,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
15,1016,2026-01-18,Divya,Bengaluru,Monitor,Electronics,1.0,NaN,Credit Card,Returned,15500

In [36]:
print(df.isnull().sum().sum())

4