# Introduction to Pandas
- Pandas is a Python library used to manipulate, clean, and analyze structured data.

In [8]:
import pandas as pd
import numpy as np

# 2. What is a Pandas Series?
- A Series is a one-dimensional labeled array. It contains values and an index.

In [10]:
import pandas as pd
marks=pd.Series([50,60,70,80,98])
print(marks)

0    50
1    60
2    70
3    80
4    98
dtype: int64

- Left side (0, 1, 2...) → index.
- Right side (85, 90...) → values.
- dtype: int64 → data type of the values.

In [22]:
import pandas as pd
prices=pd.Series([100,300,400,500])
print(prices)
print("First price:",prices[0])
print("Total:", prices.sum())
print("Average:", prices.mean())

0    100
1    300
2    400
3    500
dtype: int64
First price: 100
Total: 1300
Average: 325.0

In [24]:
marks = pd.Series(
    [85, 90, 78],
    index=["Sandeep", "Ravi", "Asha"])

print(marks)
print("Sandeep's marks:", marks["Sandeep"])

Sandeep    85
Ravi       90
Asha       78
dtype: int64
Sandeep's marks: 85

# 3. What is a Pandas DataFrame?
- A DataFrame is a two-dimensional table containing rows and columns. Different columns can have different data types.

In [27]:
import pandas as pd
data={
    "name":["Sandeep","Yashu","Ravi","Sanju","Sai"],
    "age":[23,22,20,21,22],
    "marks":[90,95,80,78,90]
}
df=pd.DataFrame(data)

In [28]:
df

      name  age  marks
0  Sandeep   23     90
1    Yashu   22     95
2     Ravi   20     80
3    Sanju   21     78
4      Sai   22     90

# Understand the code
- data is a Python dictionary.
- Dictionary keys become column names.
- Dictionary lists become column values.
- pd.DataFrame(data) creates the table.
- print(df) displays the DataFrame.

# 4. Access rows and columns
- Select one column

In [31]:
print(df["name"])

0    Sandeep
1      Yashu
2       Ravi
3      Sanju
4        Sai
Name: name, dtype: object

In [33]:
# Select multiple columns
print(df[["name","marks"]])

      name  marks
0  Sandeep     90
1    Yashu     95
2     Ravi     80
3    Sanju     78
4      Sai     90

In [34]:
# Select a row using iloc
print(df.iloc[0])

name     Sandeep
age           23
marks         90
Name: 0, dtype: object

In [35]:
print(df.iloc[1])

name     Yashu
age         22
marks       95
Name: 1, dtype: object

- iloc[0] selects the first row using its integer position.

In [36]:
# Select a particular value
print(df.iloc[0,2])

90

- Here, 0 is the first row and 2 is the third column.

In [39]:
print(df.iloc[0,1])

23

# 5. Useful DataFrame properties

In [40]:
print("Shape:", df.shape)
print("Rows and columns:", df.shape)
print("Column names:", df.columns)
print("Index:", df.index)
print("Data types:")
print(df.dtypes)

Shape: (5, 3)
Rows and columns: (5, 3)
Column names: Index(['name', 'age', 'marks'], dtype='object')
Index: RangeIndex(start=0, stop=5, step=1)
Data types:
name     object
age       int64
marks     int64
dtype: object

# Remember:
- shape → number of rows and columns.
- columns → column names.
- index → row labels.
- dtypes → data type of each column.

# 7. Real-time example: Employee analysis

In [41]:
employees = pd.DataFrame({
    "Employee": ["Ravi", "Asha", "Kiran", "Neha"],
    "Department": ["IT", "HR", "IT", "Sales"],
    "Salary": [40000, 35000, 50000, 30000})

print(employees)
print("Average salary:", employees["Salary"].mean())

print("Highest salary:", employees["Salary"].max())

print("Total salary:", employees["Salary"].sum())

  Employee Department  Salary
0     Ravi         IT   40000
1     Asha         HR   35000
2    Kiran         IT   50000
3     Neha      Sales   30000
Average salary: 38750.0
Highest salary: 50000
Total salary: 155000

In [42]:
employees

  Employee Department  Salary
0     Ravi         IT   40000
1     Asha         HR   35000
2    Kiran         IT   50000
3     Neha      Sales   30000

In [46]:
# Find employees earning more than ₹35,000:
salary=employees[employees["Salary"]>35000]
print(salary)

  Employee Department  Salary
0     Ravi         IT   40000
2    Kiran         IT   50000