In [1]:
import pandas as pd
import numpy as np

In [3]:
jan = pd.read_csv("/Users/nidagallusandeep/Downloads/day32_january_orders.csv")
feb = pd.read_csv("/Users/nidagallusandeep/Downloads/day32_january_orders(1).csv")
mar = pd.read_csv("/Users/nidagallusandeep/Downloads/day32_march_orders_extra_columns.csv")

In [6]:
jan.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [44]:
jan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10 non-null     int64
 1   Order_Date      10 non-null     object
 2   City            10 non-null     object
 3   Product         10 non-null     object
 4   Quantity        10 non-null     int64
 5   Unit_Price_INR  10 non-null     int64
 6   Order_Status    10 non-null     object
 7   Revenue_INR     10 non-null     int64
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes

In [46]:
jan.describe()

         Order_ID   Quantity  Unit_Price_INR   Revenue_INR
count    10.00000  10.000000       10.000000     10.000000
mean   3205.50000   2.100000    19750.000000  20620.000000
std       3.02765   1.449138    24879.096536  24154.999483
min    3201.00000   1.000000      700.000000   2100.000000
25%    3203.25000   1.000000      825.000000   2500.000000
50%    3205.50000   1.500000     7600.000000   8750.000000
75%    3207.75000   2.750000    44750.000000  44750.000000
max    3210.00000   5.000000    55000.000000  55000.000000

In [47]:
jan.shape

(10, 8)

In [7]:
feb.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [48]:
feb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        10 non-null     int64
 1   Order_Date      10 non-null     object
 2   City            10 non-null     object
 3   Product         10 non-null     object
 4   Quantity        10 non-null     int64
 5   Unit_Price_INR  10 non-null     int64
 6   Order_Status    10 non-null     object
 7   Revenue_INR     10 non-null     int64
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes

In [49]:
feb.describe()

         Order_ID   Quantity  Unit_Price_INR   Revenue_INR
count    10.00000  10.000000       10.000000     10.000000
mean   3205.50000   2.100000    19750.000000  20620.000000
std       3.02765   1.449138    24879.096536  24154.999483
min    3201.00000   1.000000      700.000000   2100.000000
25%    3203.25000   1.000000      825.000000   2500.000000
50%    3205.50000   1.500000     7600.000000   8750.000000
75%    3207.75000   2.750000    44750.000000  44750.000000
max    3210.00000   5.000000    55000.000000  55000.000000

In [8]:
mar.head()

,Order_ID,City,Product,Quantity,Unit_Price_INR,Payment_Method,Revenue_INR
0,3221,Hyderabad,Mouse,2,700,UPI,1400
1,3222,Bengaluru,Monitor,1,14000,Card,14000
2,3223,Chennai,Laptop,1,55000,UPI,55000
3,3224,Vijayawada,Keyboard,3,1200,Cash,3600
4,3225,Hyderabad,Mouse,4,700,Card,2800

In [50]:
mar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        5 non-null      int64
 1   City            5 non-null      object
 2   Product         5 non-null      object
 3   Quantity        5 non-null      int64
 4   Unit_Price_INR  5 non-null      int64
 5   Payment_Method  5 non-null      object
 6   Revenue_INR     5 non-null      int64
dtypes: int64(4), object(3)
memory usage: 412.0+ bytes

In [51]:
mar.describe()

          Order_ID  Quantity  Unit_Price_INR  Revenue_INR
count     5.000000   5.00000        5.000000      5.00000
mean   3223.000000   2.20000    14320.000000  15360.00000
std       1.581139   1.30384    23441.992236  22716.24969
min    3221.000000   1.00000      700.000000   1400.00000
25%    3222.000000   1.00000      700.000000   2800.00000
50%    3223.000000   2.00000     1200.000000   3600.00000
75%    3224.000000   3.00000    14000.000000  14000.00000
max    3225.000000   4.00000    55000.000000  55000.00000

In [15]:
# Example 1 — Combine January and February
result = pd.concat([jan, feb])
result.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [14]:
# Example 2 — Combine with reset index
result = pd.concat(
    [jan, feb],
    ignore_index=True)
result.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [13]:
# Example 3 — Combine three DataFrames
result = pd.concat(
    [jan, feb, mar],
    ignore_index=True)
result.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Payment_Method
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000,NaN
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100,NaN
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400,NaN
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000,NaN
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800,NaN

In [16]:
# Example 4 — Check combined shape
result.shape

(20, 8)

In [18]:
# Example 5 — Combine only selected columns
result = pd.concat([
    jan[["Order_ID", "City", "Revenue_INR"]],
    feb[["Order_ID", "City", "Revenue_INR"]]
], ignore_index=True)
result.head()

   Order_ID        City  Revenue_INR
0      3201   Hyderabad        55000
1      3202   Bengaluru         2100
2      3203     Chennai         2400
3      3204  Vijayawada        14000
4      3205   Hyderabad         2800

In [20]:
# Example 6 — Combine rows
pd.concat([jan, feb], axis=0, ignore_index=True).head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [21]:
# Example 7 — Combine columns
pd.concat([jan, feb], axis=1)

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800
5,3206,2026-01-18,Bengaluru,Laptop,1,55000,Returned,55000,3206,2026-01-18,Bengaluru,Laptop,1,55000,Returned,55000
6,3207,2026-01-21,Chennai,Monitor,1,14000,Delivered,14000,3207,2026-01-21,Chennai,Monitor,1,14000,Delivered,14000
7,3208,2026-01-24,Vijayawada,Keyboard,2,1200,Delivered,2400,3208,2026-01-24,Vijayawada,Keyboard,2,1200,Delivered,2400
8,3209,2026-01-27,Hyderabad,Laptop,1,55000,Delivered,55000,3209,2026-01-27,Hyderabad,Laptop,1,55000,Delivered,55000
9,3210,2026-01-30,Bengaluru,Mouse,5,700,Delivered,3500,3210,2026-01-30,Bengaluru,Mouse,5,700,Delivered,3500

- Note: axis=1 aligns rows by index. It does not match orders by Order_ID.

In [22]:
# Example 8 — Combine selected columns side by side
pd.concat([
    jan[["Order_ID", "City"]],
    jan[["Product", "Revenue_INR"]]], axis=1)

   Order_ID        City   Product  Revenue_INR
0      3201   Hyderabad    Laptop        55000
1      3202   Bengaluru     Mouse         2100
2      3203     Chennai  Keyboard         2400
3      3204  Vijayawada   Monitor        14000
4      3205   Hyderabad     Mouse         2800
5      3206   Bengaluru    Laptop        55000
6      3207     Chennai   Monitor        14000
7      3208  Vijayawada  Keyboard         2400
8      3209   Hyderabad    Laptop        55000
9      3210   Bengaluru     Mouse         3500

In [24]:
# Example 9 — Keep original index
pd.concat([jan, feb], ignore_index=False).head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [25]:
# Example 10 — Add source labels using keys
result = pd.concat(
    [jan, feb],
    keys=["January", "February"])

result

            Order_ID  Order_Date        City   Product  Quantity  \
January  0      3201  2026-01-03   Hyderabad    Laptop         1
         1      3202  2026-01-06   Bengaluru     Mouse         3
         2      3203  2026-01-09     Chennai  Keyboard         2
         3      3204  2026-01-12  Vijayawada   Monitor         1
         4      3205  2026-01-15   Hyderabad     Mouse         4
         5      3206  2026-01-18   Bengaluru    Laptop         1
         6      3207  2026-01-21     Chennai   Monitor         1
         7      3208  2026-01-24  Vijayawada  Keyboard         2
         8      3209  2026-01-27   Hyderabad    Laptop         1
         9      3210  2026-01-30   Bengaluru     Mouse         5
February 0      3201  2026-01-03   Hyderabad    Laptop         1
         1      3202  2026-01-06   Bengaluru     Mouse         3
         2      3203  2026-01-09     Chennai  Keyboard         2
         3      3204  2026-01-12  Vijayawada   Monitor         1
         4      3205  2026-01-15   Hyderabad     Mouse         4
         5      3206  2026-01-18   Bengaluru    Laptop         1
         6      3207  2026-01-21     Chennai   Monitor         1
         7      3208  2026-01-24  Vijayawada  Keyboard         2
         8      3209  2026-01-27   Hyderabad    Laptop         1
         9      3210  2026-01-30   Bengaluru     Mouse         5

            Unit_Price_INR Order_Status  Revenue_INR
January  0           55000    Delivered        55000
         1             700    Delivered         2100
         2            1200    Cancelled         2400
         3           14000    Delivered        14000
         4             700    Delivered         2800
         5           55000     Returned        55000
         6           14000    Delivered        14000
         7            1200    Delivered         2400
         8           55000    Delivered        55000
         9             700    Delivered         3500
February 0           55000    Delivered        55000
         1             700    Delivered         2100
         2            1200    Cancelled         2400
         3           14000    Delivered        14000
         4             700    Delivered         2800
         5           55000     Returned        55000
         6           14000    Delivered        14000
         7            1200    Delivered         2400
         8           55000    Delivered        55000
         9             700    Delivered         3500

In [28]:
# Example 11 — Drop old index
result = pd.concat(
    [jan, feb],
    ignore_index=True)
result.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800

In [29]:
# Example 12 — Inner join on columns
result = pd.concat(
    [jan, mar],
    join="inner",
    ignore_index=True)
result.head()

   Order_ID        City   Product  Quantity  Unit_Price_INR  Revenue_INR
0      3201   Hyderabad    Laptop         1           55000        55000
1      3202   Bengaluru     Mouse         3             700         2100
2      3203     Chennai  Keyboard         2            1200         2400
3      3204  Vijayawada   Monitor         1           14000        14000
4      3205   Hyderabad     Mouse         4             700         2800

In [30]:
# Example 13 — Outer join on columns
result = pd.concat(
    [jan, mar],
    join="outer",
    ignore_index=True)
result.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Payment_Method
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000,NaN
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100,NaN
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400,NaN
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000,NaN
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800,NaN

- join="outer" keeps all columns. Missing values are filled with NaN.

In [33]:
# Example 14 — Check missing values after concat
result = pd.concat(
    [jan, mar],
    ignore_index=True)
result.isnull().sum()

Order_ID           0
Order_Date         5
City               0
Product            0
Quantity           0
Unit_Price_INR     0
Order_Status       5
Revenue_INR        0
Payment_Method    10
dtype: int64

In [35]:
# Example 15 — Remove duplicate rows after concat
result = pd.concat(
    [jan, feb],
    ignore_index=True)

result = result.drop_duplicates()

In [36]:
# Example 16 — Sort combined orders by revenue
result = pd.concat(
    [jan, feb],
    ignore_index=True
)

result.sort_values(
    "Revenue_INR",
    ascending=False
)

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
5,3206,2026-01-18,Bengaluru,Laptop,1,55000,Returned,55000
18,3209,2026-01-27,Hyderabad,Laptop,1,55000,Delivered,55000
15,3206,2026-01-18,Bengaluru,Laptop,1,55000,Returned,55000
8,3209,2026-01-27,Hyderabad,Laptop,1,55000,Delivered,55000
10,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
6,3207,2026-01-21,Chennai,Monitor,1,14000,Delivered,14000
13,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
16,3207,2026-01-21,Chennai,Monitor,1,14000,Delivered,14000
9,3210,2026-01-30,Bengaluru,Mouse,5,700,Delivered,3500
19,3210,2026-01-30,Bengaluru,Mouse,5,700,Delivered,3500
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800
14,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800
7,3208,2026-01-24,Vijayawada,Keyboard,2,1200,Delivered,2400
12,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
17,3208,2026-01-24,Vijayawada,Keyboard,2,1200,Delivered,2400
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
11,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100

In [38]:
# Example 17 — Filter delivered orders after concat
result = pd.concat(
    [jan, feb],
    ignore_index=True)
result[result["Order_Status"] == "Delivered"]

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800
6,3207,2026-01-21,Chennai,Monitor,1,14000,Delivered,14000
7,3208,2026-01-24,Vijayawada,Keyboard,2,1200,Delivered,2400
8,3209,2026-01-27,Hyderabad,Laptop,1,55000,Delivered,55000
9,3210,2026-01-30,Bengaluru,Mouse,5,700,Delivered,3500
10,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000
11,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100
13,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000
14,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800
16,3207,2026-01-21,Chennai,Monitor,1,14000,Delivered,14000
17,3208,2026-01-24,Vijayawada,Keyboard,2,1200,Delivered,2400
18,3209,2026-01-27,Hyderabad,Laptop,1,55000,Delivered,55000
19,3210,2026-01-30,Bengaluru,Mouse,5,700,Delivered,3500

In [40]:
# Example 18 — Calculate total monthly revenue
result = pd.concat(
    [jan, feb],
    ignore_index=True)

result.groupby("City")["Revenue_INR"].sum()

City
Bengaluru     121200
Chennai        32800
Hyderabad     225600
Vijayawada     32800
Name: Revenue_INR, dtype: int64

In [42]:
# Example 19 — Create month-wise DataFrame labels
jan_copy = jan.copy()
feb_copy = feb.copy()
jan_copy["Month"] = "January"
feb_copy["Month"] = "February"
result = pd.concat(
    [jan_copy, feb_copy],
    ignore_index=True)

result.head()

,Order_ID,Order_Date,City,Product,Quantity,Unit_Price_INR,Order_Status,Revenue_INR,Month
0,3201,2026-01-03,Hyderabad,Laptop,1,55000,Delivered,55000,January
1,3202,2026-01-06,Bengaluru,Mouse,3,700,Delivered,2100,January
2,3203,2026-01-09,Chennai,Keyboard,2,1200,Cancelled,2400,January
3,3204,2026-01-12,Vijayawada,Monitor,1,14000,Delivered,14000,January
4,3205,2026-01-15,Hyderabad,Mouse,4,700,Delivered,2800,January

In [43]:
# Example 20 — Complete combined sales report
jan_copy = jan.copy()
feb_copy = feb.copy()

jan_copy["Month"] = "January"
feb_copy["Month"] = "February"
final_df = pd.concat(
    [jan_copy, feb_copy],
    ignore_index=True)
sales_report = final_df.groupby("Month").agg(
    Total_Orders=("Order_ID", "count"),
    Total_Quantity=("Quantity", "sum"),
    Total_Revenue=("Revenue_INR", "sum"))

sales_report

          Total_Orders  Total_Quantity  Total_Revenue
Month
February            10              21         206200
January             10              21         206200