In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day20_retail_orders.csv")

In [4]:
df.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,4001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-02-01,55000
1,4002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-02-02,1400
2,4003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-02-03,1200
3,4004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-02-04,52000
4,4005,NaN,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-02-05,30000

In [5]:
df.shape

(25, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        25 non-null     int64
 1   Customer_Name   24 non-null     object
 2   City            25 non-null     object
 3   Product         25 non-null     object
 4   Category        25 non-null     object
 5   Quantity        24 non-null     float64
 6   Unit_Price_INR  25 non-null     int64
 7   Payment_Method  24 non-null     object
 8   Order_Status    25 non-null     object
 9   Order_Date      25 non-null     object
 10  Revenue_INR     25 non-null     int64
dtypes: float64(1), int64(3), object(7)
memory usage: 2.3+ KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

Order_ID          0
Customer_Name     1
City              0
Product           0
Category          0
Quantity          1
Unit_Price_INR    0
Payment_Method    1
Order_Status      0
Order_Date        0
Revenue_INR       0
dtype: int64

In [12]:
df["Customer_Name"]=df["Customer_Name"].fillna(df["Customer_Name"].mode()[0])
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean())
df["Payment_Method"]=df["Payment_Method"].fillna(df["Payment_Method"].mode()[0])

In [13]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Payment_Method    0
Order_Status      0
Order_Date        0
Revenue_INR       0
dtype: int64

In [16]:
# Select a single column
df["Product"].head()

0      Laptop
1       Mouse
2    Keyboard
3      Laptop
4     Monitor
Name: Product, dtype: object

In [17]:
# To select customer names:
df["Customer_Name"].head()

0       Ravi
1       Asha
2    Sandeep
3       Neha
4       Ajay
Name: Customer_Name, dtype: object

In [18]:
# To select revenue:
df["Revenue_INR"].head()

0    55000
1     1400
2     1200
3    52000
4    30000
Name: Revenue_INR, dtype: int64

In [19]:
# Select multiple columns
df[["City","Product","Category"]].head()

        City   Product     Category
0  Hyderabad    Laptop  Electronics
1  Bengaluru     Mouse  Accessories
2  Hyderabad  Keyboard  Accessories
3    Chennai    Laptop  Electronics
4       Pune   Monitor  Electronics

In [20]:
df[["Payment_Method","Customer_Name"]].head()

  Payment_Method Customer_Name
0            UPI          Ravi
1    Credit Card          Asha
2            UPI       Sandeep
3     Debit Card          Neha
4            UPI          Ajay

# Select rows using iloc[]
- iloc[] selects rows and columns using integer positions, starting from zero.

In [21]:
# First row
df.iloc[0]

Order_ID                 4001
Customer_Name            Ravi
City                Hyderabad
Product                Laptop
Category          Electronics
Quantity                  1.0
Unit_Price_INR          55000
Payment_Method            UPI
Order_Status        Delivered
Order_Date         2026-02-01
Revenue_INR             55000
Name: 0, dtype: object

In [22]:
# First three rows
df.iloc[0:3]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,4001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-02-01,55000
1,4002,Asha,Bengaluru,Mouse,Accessories,2.0,700,Credit Card,Delivered,2026-02-02,1400
2,4003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-02-03,1200

In [25]:
df.iloc[0:1]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,4001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-02-01,55000

In [26]:
# First three rows and first two columns
df.iloc[0:3,0:2]

   Order_ID Customer_Name
0      4001          Ravi
1      4002          Asha
2      4003       Sandeep

# Select data using loc[]
- loc[] selects data using row labels and column names.

In [28]:
# First row by its label
df.loc[0]

Order_ID                 4001
Customer_Name            Ravi
City                Hyderabad
Product                Laptop
Category          Electronics
Quantity                  1.0
Unit_Price_INR          55000
Payment_Method            UPI
Order_Status        Delivered
Order_Date         2026-02-01
Revenue_INR             55000
Name: 0, dtype: object

In [30]:
# Select customer and product columns
df.loc[:, ["Customer_Name", "Product"]].head()

  Customer_Name   Product
0          Ravi    Laptop
1          Asha     Mouse
2       Sandeep  Keyboard
3          Neha    Laptop
4          Ajay   Monitor

In [31]:
# Select rows with labels 0 through 4, inclusive
df.loc[0:4, ["Order_ID", "Product"]]

   Order_ID   Product
0      4001    Laptop
1      4002     Mouse
2      4003  Keyboard
3      4004    Laptop
4      4005   Monitor

In [37]:
expensive = df.loc[df["Unit_Price_INR"] > 10000,["Order_ID", "Product", "Unit_Price_INR"]]
expensive

    Order_ID  Product  Unit_Price_INR
0       4001   Laptop           55000
3       4004   Laptop           52000
4       4005  Monitor           15000
6       4007   Laptop           56000
8       4009  Monitor           14500
9       4010   Laptop           54000
11      4012  Monitor           14000
13      4014   Laptop           53000
15      4016  Monitor           15500
17      4018   Laptop           57000
19      4020  Monitor           14800
20      4021   Laptop           51000
23      4024   Laptop           53500
24      4025  Monitor           15200

In [36]:
laptop_orders = df.loc[df["Product"] == "Laptop"]
laptop_orders

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,4001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-02-01,55000
3,4004,Neha,Chennai,Laptop,Electronics,1.0,52000,Debit Card,Delivered,2026-02-04,52000
6,4007,Arjun,Bengaluru,Laptop,Electronics,1.0,56000,Credit Card,Delivered,2026-02-07,56000
9,4010,Sneha,Hyderabad,Laptop,Electronics,1.0,54000,UPI,Delivered,2026-02-10,54000
13,4014,Pooja,Bengaluru,Laptop,Electronics,1.0,53000,Debit Card,Delivered,2026-02-14,53000
17,4018,Kavya,Pune,Laptop,Electronics,1.0,57000,UPI,Delivered,2026-02-18,57000
20,4021,Rohit,Hyderabad,Laptop,Electronics,1.0,51000,UPI,Delivered,2026-02-21,51000
23,4024,Nandini,Hyderabad,Laptop,Electronics,1.0,53500,UPI,Delivered,2026-02-24,53500

In [40]:
# Find delivered orders from Hyderabad
result = df.loc[(df["City"] == "Hyderabad") &(df["Order_Status"] == "Delivered"),["Order_ID", "Customer_Name", "Product", "Order_Status"]]
result

    Order_ID Customer_Name   Product Order_Status
0       4001          Ravi    Laptop    Delivered
2       4003       Sandeep  Keyboard    Delivered
5       4006         Priya     Mouse    Delivered
9       4010         Sneha    Laptop    Delivered
14      4015        Nikhil     Mouse    Delivered
18      4019           Sai     Mouse    Delivered
20      4021         Rohit    Laptop    Delivered
23      4024       Nandini    Laptop    Delivered

In [43]:
# Select orders paid through UPI
upi_orders = df.loc[df["Payment_Method"] == "UPI"].head()
upi_orders

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Order_Date,Revenue_INR
0,4001,Ravi,Hyderabad,Laptop,Electronics,1.0,55000,UPI,Delivered,2026-02-01,55000
2,4003,Sandeep,Hyderabad,Keyboard,Accessories,1.0,1200,UPI,Delivered,2026-02-03,1200
4,4005,Ajay,Pune,Monitor,Electronics,2.0,15000,UPI,Cancelled,2026-02-05,30000
7,4008,Divya,Chennai,Keyboard,Accessories,2.0,1100,UPI,Delivered,2026-02-08,2200
8,4009,Manoj,Pune,Monitor,Electronics,1.0,14500,UPI,Returned,2026-02-09,14500

In [44]:
# Get the first five products and prices
print(df.iloc[:5, [3, 6]])

    Product  Unit_Price_INR
0    Laptop           55000
1     Mouse             700
2  Keyboard            1200
3    Laptop           52000
4   Monitor           15000