In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day23_missing_values.csv")

In [4]:
df.head()

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
0,2001,Sandeep,Hyderabad,Laptop,Electronics,1.0,55000.0,UPI,Delivered,55000.0
1,2002,Ravi,Bengaluru,Mouse,Accessories,2.0,800.0,NaN,Delivered,1600.0
2,2003,Priya,Chennai,Monitor,Electronics,1.0,NaN,Card,Returned,NaN
3,2004,NaN,Pune,Keyboard,Accessories,1.0,1500.0,Cash,Delivered,1500.0
4,2005,Divya,Hyderabad,Laptop,Electronics,NaN,62000.0,UPI,Cancelled,NaN

In [5]:
df.shape

(30, 10)

In [7]:
df.size

300

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        30 non-null     int64
 1   Customer_Name   29 non-null     object
 2   City            29 non-null     object
 3   Product         30 non-null     object
 4   Category        30 non-null     object
 5   Quantity        29 non-null     float64
 6   Unit_Price_INR  29 non-null     float64
 7   Payment_Method  27 non-null     object
 8   Order_Status    30 non-null     object
 9   Revenue_INR     28 non-null     float64
dtypes: float64(3), int64(1), object(6)
memory usage: 2.5+ KB

In [9]:
df.isnull().sum()

Order_ID          0
Customer_Name     1
City              1
Product           0
Category          0
Quantity          1
Unit_Price_INR    1
Payment_Method    3
Order_Status      0
Revenue_INR       2
dtype: int64

In [10]:
df[df["Payment_Method"].isna()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
1,2002,Ravi,Bengaluru,Mouse,Accessories,2.0,800.0,NaN,Delivered,1600.0
8,2009,Lakshmi,Hyderabad,Keyboard,Accessories,2.0,1400.0,NaN,Returned,2800.0
21,2022,Kavya,Bengaluru,Mouse,Accessories,2.0,900.0,NaN,Returned,1800.0

In [11]:
# Remove rows containing any missing value
df_clean = df.dropna()
print(df_clean.shape)

(23, 10)

In [12]:
# Remove rows only when Customer_Name is missing
df_clean = df.dropna(subset=["Customer_Name"])

In [13]:
# Remove columns that contain missing values
df_clean = df.dropna(axis=1)

In [15]:
# fillna() — Fill missing values
df["Customer_Name"] = df["Customer_Name"].fillna("Unknown")

In [18]:
# Fill missing cities with the most frequent city
most_common_city = df["City"].mode()[0]
df["City"] = df["City"].fillna(most_common_city)

In [19]:
#Fill missing quantity with median
median_quantity = df["Quantity"].median()

df["Quantity"] = df["Quantity"].fillna(
    median_quantity
)

In [20]:
# Fill missing price with median
median_price = df["Unit_Price_INR"].median()
df["Unit_Price_INR"] = df["Unit_Price_INR"].fillna(
    median_price)

In [22]:
df[df["Payment_Method"].isna()]

,Order_ID,Customer_Name,City,Product,Category,Quantity,Unit_Price_INR,Payment_Method,Order_Status,Revenue_INR
1,2002,Ravi,Bengaluru,Mouse,Accessories,2.0,800.0,NaN,Delivered,1600.0
8,2009,Lakshmi,Hyderabad,Keyboard,Accessories,2.0,1400.0,NaN,Returned,2800.0
21,2022,Kavya,Bengaluru,Mouse,Accessories,2.0,900.0,NaN,Returned,1800.0

In [30]:
df["Payment_Method"] = df["Payment_Method"].fillna(
    df["Payment_Method"].mode()[0]
)

In [31]:
print(df["Payment_Method"].isna().sum())

0

In [32]:
df["Revenue_INR"] = df["Quantity"] * df["Unit_Price_INR"]

In [33]:
# Check missing values after cleaning
print(df.isna().sum())

Order_ID          0
Customer_Name     0
City              0
Product           0
Category          0
Quantity          0
Unit_Price_INR    0
Payment_Method    0
Order_Status      0
Revenue_INR       0
dtype: int64