In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/day24_duplicate_orders.csv")

In [5]:
df.head()

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Payment_Method,Order_Status
0,3001,Sandeep,Hyderabad,Laptop,1,55000,UPI,Delivered
1,3002,Ravi,Bengaluru,Mouse,2,800,Card,Delivered
2,3003,Priya,Chennai,Monitor,1,12500,UPI,Returned
3,3004,Anil,Pune,Keyboard,1,1500,Cash,Delivered
4,3005,Divya,Hyderabad,Laptop,1,62000,UPI,Cancelled

In [6]:
df.shape

(34, 8)

In [11]:
df.tail()

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Payment_Method,Order_Status
29,3030,Bhavya,Bengaluru,Laptop,1,60500,Card,Delivered
30,3003,Priya,Chennai,Monitor,1,12500,UPI,Returned
31,3006,Kiran,Bengaluru,Monitor,2,11800,Card,Delivered
32,3013,Pooja,Hyderabad,Monitor,1,12800,UPI,Delivered
33,3020,Swathi,Pune,Laptop,1,59000,UPI,Cancelled

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        34 non-null     int64
 1   Customer_Name   34 non-null     object
 2   City            34 non-null     object
 3   Product         34 non-null     object
 4   Quantity        34 non-null     int64
 5   Unit_Price_INR  34 non-null     int64
 6   Payment_Method  34 non-null     object
 7   Order_Status    34 non-null     object
dtypes: int64(3), object(5)
memory usage: 2.3+ KB

In [9]:
df.size

272

In [10]:
df.describe()

          Order_ID   Quantity  Unit_Price_INR
count    34.000000  34.000000       34.000000
mean   3014.911765   1.617647    25061.764706
std       8.719076   0.985184    26328.090365
min    3001.000000   1.000000      650.000000
25%    3007.250000   1.000000     1462.500000
50%    3014.500000   1.000000    12500.000000
75%    3021.750000   2.000000    57750.000000
max    3030.000000   5.000000    64000.000000

# duplicated() — Find duplicate rows
- False means the row is not a duplicate of an earlier row.
- True means the row repeats an earlier row across all columns.

In [13]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
32     True
33     True
dtype: bool

In [14]:
# Count duplicate rows
print(df.duplicated().sum())

4

In [15]:
# Display duplicate rows
df[df.duplicated()]

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Payment_Method,Order_Status
30,3003,Priya,Chennai,Monitor,1,12500,UPI,Returned
31,3006,Kiran,Bengaluru,Monitor,2,11800,Card,Delivered
32,3013,Pooja,Hyderabad,Monitor,1,12800,UPI,Delivered
33,3020,Swathi,Pune,Laptop,1,59000,UPI,Cancelled

- This shows the repeated rows, excluding the first occurrence.

# drop_duplicates() — Remove duplicates

In [23]:
df_clean=df.drop_duplicates()
print("Before:", df.shape)
print("After:", df_clean.shape)

Before: (34, 8)
After: (30, 8)

In [24]:
# Remove duplicates using a specific column
df_clean = df.drop_duplicates(subset=["Order_ID"])

In [26]:
# Keep the last occurrence
df_clean = df.drop_duplicates(keep="last")

# Options:
- keep="first" — keep the first occurrence (default).
- keep="last" — keep the last occurrence.
- keep=False — remove every row that belongs to a duplicate group.

In [27]:
# Check duplicates using multiple columns
df.duplicated(subset=["Customer_Name", "Product"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
32     True
33     True
dtype: bool

In [28]:
# Find duplicate order IDs
df[df.duplicated(subset=["Order_ID"], keep=False)]

,Order_ID,Customer_Name,City,Product,Quantity,Unit_Price_INR,Payment_Method,Order_Status
2,3003,Priya,Chennai,Monitor,1,12500,UPI,Returned
5,3006,Kiran,Bengaluru,Monitor,2,11800,Card,Delivered
12,3013,Pooja,Hyderabad,Monitor,1,12800,UPI,Delivered
19,3020,Swathi,Pune,Laptop,1,59000,UPI,Cancelled
30,3003,Priya,Chennai,Monitor,1,12500,UPI,Returned
31,3006,Kiran,Bengaluru,Monitor,2,11800,Card,Delivered
32,3013,Pooja,Hyderabad,Monitor,1,12800,UPI,Delivered
33,3020,Swathi,Pune,Laptop,1,59000,UPI,Cancelled

In [29]:
# Remove exact duplicates and reset the index
df_clean = (df.drop_duplicates().reset_index(drop=True))
print(df_clean.shape)

(30, 8)

In [30]:
# Check whether duplicates remain
print(df_clean.duplicated().sum())

0